### ISSUE TITLE
AzureSQL - select query running few days

### ISSUE THREAD

**Issue by SqlAdmin** [TeamSQL/desktop-app#100]
OS: Windows_NT x64 10.0.15063
VERSION: 0.9.91
---------------
Database Type: **AzureSQL**
Issue: When I ran a select statement against an Azure SQL in _SSMS_, I can able to get the results within  a _second_, but I tried the same query in TeamSQL, but it took more time, still running I didn't show any error message or any results.

**Comment by abacigil** [comment]
@SqlAdmin can you send us an email/DM so we can check your logs if there is an error our side.
