### ISSUE TITLE
SHH tunnel with encrypted private key

### ISSUE THREAD

**Issue by iushev** [TeamSQL/desktop-app#104]
OS: Linux x64 4.4.0-75-generic
VERSION: 0.9.91
---------------
Database Type: PostgreSQL 9.5.6 
I made connection with SSH tunnel using private key. My key is encrypted. When I try to connect I receive this error.
![image](https://cloud.githubusercontent.com/assets/3023174/25691917/b919a36e-30a7-11e7-90c0-b889185d1511.png)

**Comment by dagoodma** [comment]
I'm having the same issue.  Does this really not work?  I can't believe they charge money for this app.

**Comment by abacigil** [comment]
Fixed in the latest release.
