### ISSUE TITLE
Add ability to "Auto-Reformat query"

### ISSUE THREAD

**Issue by ostaplisovyj** [TeamSQL/desktop-app#108]
It would be great to have some auto-format query feature (similar to JetBrain's WebStorm or DataGRIP), since in many cases there's a need to copy/paste some query for testing, and it pastes in a single line

**Comment by guitarzan** [comment]
[ApexSQL](http://www.apexsql.com/sql_tools_refactor.aspx) has a great SSMS plugin for this. Maybe reach out to them?

**Comment by AngelMunoz** [comment]
also a keybinding for formating wouldn't be that bad :space_invader:
