### ISSUE TITLE
No connection success, but test connection 

### ISSUE THREAD

**Issue by drg-michael** [TeamSQL/desktop-app#109]
OS: Darwin x64 16.5.0
VERSION: 0.9.93
---------------
Database Type: MSSQL 2008 r2 (Windows server 2008)
How can this issue be reproduced?
in edit connection o new connection, When filling out the form, I press the "Test Connection" button, and it is done successfully, but at the moment of making the connection to the server, first send me a message that is taking a long time, press the "keep connection" button and immediately Then send me a message: "Connection failed to the server. Please check your connection settings"

**Comment by abacigil** [comment]
Hi @drg-michael , can you try to connect with the latest version ( 0.9.97, just released ), and if that continues, please send me an email/DM so I can check error logs.
