### ISSUE TITLE
MySQL Connection - With SSH Tunnel

### ISSUE THREAD

**Issue by WebMDT-Marco** [TeamSQL/desktop-app#110]
OS: Darwin x64 16.5.0
VERSION: 0.9.93
---------------
Database Type: MySQL with SSH Tunnel

Connection is successful during "TEST CONNECTION" (message: Provided connection properties worked correctly. ) but does not work from the explorer. 

Existing connections could not be restarted due to SSH connection error.
onnect ECONNREFUSED *MYIP*:22

The error shows that its trying to SSH using port 22, even though I changed it to a different port (as its mapped differently on our server).

**Comment by erenbaydemir** [comment]
This issue was fixed several updates ago. Do you still experience that problem? 

#111
