### ISSUE TITLE
Timeout when I use SSH Tunnel

### ISSUE THREAD

**Issue by DamixSwayware** [TeamSQL/desktop-app#111]
OS: Linux x64 4.10.0-041000-lowlatency
VERSION: 0.9.93
---------------
Database Type: MySQL
When I click the test button in the connection edit box everything is fine (successfully connected), but after saving the connection I can't connect to the server. I get this information: "Connection failed to the server. Please check your connection settings".

**Comment by erenbaydemir** [comment]
Hi @DamixSwayware , a similar bug was fixed several updates ago. Do you still experience that problem? 

Thank you.
