### ISSUE TITLE
TeamSQL and Proxy server

### ISSUE THREAD

**Issue by BMarvi** [TeamSQL/desktop-app#112]
OS: Windows_NT x64 10.0.10586
VERSION: 0.9.93
---------------
Database Type: ALL
How can this issue be reproduced?

seems that teamsql ignores system proxy settings, and I can't find a way to configure it inside the program. 
As my corporate network permit internet access only by proxy, it results impossibile to login.

**Comment by abacigil** [comment]
Hi there,

We just released an update and it has proxy support, please try to set your proxy setting in TeamSQL.

You can open proxy settings from login screen's menu Settings -> Proxy Settings or if you've already logged in, it's in File menu.

![screen shot 2017-06-23 at 12 31 04](https://user-images.githubusercontent.com/759174/27476053-f4e99e3c-580f-11e7-92ae-28920d0be124.png)

![screen shot 2017-06-23 at 12 31 31](https://user-images.githubusercontent.com/759174/27476060-f93aae54-580f-11e7-941f-7002c271317b.png)

![screen shot 2017-06-23 at 12 31 42](https://user-images.githubusercontent.com/759174/27476066-fcaea5fe-580f-11e7-8700-bcaea0523d12.png)

**Comment by shree3176** [comment]
What is to be added in Proxy Settings??
