### ISSUE TITLE
Using variables inside queries

### ISSUE THREAD

**Issue by maxmarkus** [TeamSQL/desktop-app#115]
Hi there, 
Really great work so far, I love the style of the mac app as it feels similar to my beloved VisualStudio Code.

One feature which I would really love to see is using variables when building queries, also code completion should be adapted then of course. 
I have some apps that programmatically create similar tables with different names, so something like that:

    $table = 'mytable';
    $user_id = 1554;
    SELECT * FROM data_${table} d where d.user_id = ${user_id}`;

Best, Markus

**Comment by abacigil** [comment]
Hi @maxmarkus , we just released Custom Snippets: https://blog.teamsql.io/custom-snippets-4b053436c5a7

I know it's not exactly what you want, but I thought it can help you in a way.
