### ISSUE TITLE
TeamSQL doesn't show PostgreSQL Public tables 

### ISSUE THREAD

**Issue by rasputino** [TeamSQL/desktop-app#116]
OS: Windows_NT x64 10.0.14393
VERSION: 0.9.95
---------------
Database Type: PostgreSQL 9.3.5 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4), 64-bit

Is the same issue than #42 but it still unresolved

![image](https://cloud.githubusercontent.com/assets/2887216/26401614/01ee9d30-4087-11e7-800b-5c6d666ae42a.png)

**Comment by abacigil** [comment]
Hi @rasputino , you don't see "public" schema in schema list after you connect to PostgreSQL database or you see "public" schema but no tables in "public" schema?

**Comment by rasputino** [comment]
I didn't see anything
![teamsqlerror](https://cloud.githubusercontent.com/assets/2887216/26442934/d674eff0-4136-11e7-895f-03544b3efd4e.gif)

**Comment by abacigil** [comment]
Ok, we simply run this SQL command to get schema list:

`select schema_name from information_schema.schemata where schema_name not like 
                    'pg_%' and schema_name != 'information_schema' ORDER BY schema_name DESC`

what do you get when you run it? do you see public in there?

**Comment by aburakovskiy** [comment]
Strange behavior, if I run this query I do not get **public** schema nowhere
![2017-05-25_1220_](https://cloud.githubusercontent.com/assets/1153385/26444768/6a61ce68-4146-11e7-8945-91fc12b6821a.png)
the same result in PgAdmin, but I see **public** schema there
<img width="246" alt="2017-05-25_1242" src="https://cloud.githubusercontent.com/assets/1153385/26445105/9c0353be-4147-11e7-8710-a086151780fe.png">

**Comment by abacigil** [comment]
I want to be sure before I write detailed explanation, can you try to create a schema named "public"

after you connect to shard_2, run 

`CREATE SCHEMA "public"`

if it says public schema exists, can you run a select command:

`SELECT * FROM public.XXX`

what does it return @rasputino ?

**Comment by abacigil** [comment]
@rasputino can you also run:
`select schema_name from information_schema.schemata ORDER BY schema_name DESC`

**Comment by aburakovskiy** [comment]
Yes `CREATE SCHEMA "public"` says public schema exists in pgAdmin, but in TeamSQL it write "Running ..." and never ends
`SELECT * FROM public.XXX` works great and return data rows

**Comment by rasputino** [comment]
The queries 
`select schema_name from information_schema.schemata  where schema_name not like 'pg_%' and schema_name != 'information_schema' ORDER BY schema_name DESC`
and
`select schema_name from information_schema.schemata ORDER BY schema_name DESC`
show me nothing, just the column name "schema_name" and no results

This is the schema DDL:
```
-- Schema: public

-- DROP SCHEMA public;

CREATE SCHEMA public
  AUTHORIZATION postgres;

GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
GRANT ALL ON SCHEMA public TO _<USER_I_AM_USING>_;
COMMENT ON SCHEMA public
  IS 'standard public schema'; 
```

The query
`select * from information_schema.tables where table_schema = 'public'`
shows me one row but pgadmin shows my three rows something really strange...

**Comment by abacigil** [comment]
@aburakovskiy We've found a bug about "Running..." state. There will be a hot fix today.

Still checking "public" schema issue, will update you guys possibly today.

**Comment by abacigil** [comment]
@rasputino @aburakovskiy please check: https://stackoverflow.com/a/21783658

**Comment by abacigil** [comment]
@rasputino @aburakovskiy We've released a new version ( 0.9.96 ) which fixes "Running" issue, release notes are here: https://headwayapp.co/teamsql-release-notes

**Comment by aburakovskiy** [comment]
As I understood, it shows **public** scheme only for superuser. But what trick does pgAdmin do to show it for the same user, as for TeamSQL

**Comment by aburakovskiy** [comment]
And yes, it works well with a newer version of postgresql (9.5.7)
<img width="221" alt="2017-06-23_1349" src="https://user-images.githubusercontent.com/1153385/27479084-f2c5c8a0-581a-11e7-8ae0-22448e2b3288.png">

**Comment by paguii** [comment]
Hello, i'm having the same issues today.

My OS:
Ubuntu 16.04 LTS

My version of postgres:
PostgreSQL 9.3.19 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

![captura de tela de 2018-04-09 10-45-32](https://user-images.githubusercontent.com/18687395/38501417-5a2c8ed2-3be3-11e8-891f-89282b055696.png)
