### ISSUE TITLE
Linux RPM version

### ISSUE THREAD

**Issue by deafjava** [TeamSQL/desktop-app#119]
You released Ubuntu (DEB), it's nice! It's interesting that you could also release a CentOS/Fedora version (RPM).

**Comment by gabrielbc** [comment]
+1

**Comment by vzool** [comment]
Hi,

What is happened to this request? #129

Thanks for the great job

**Comment by murteza** [comment]
Hi @deafjava @gabrielbc , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
