### ISSUE TITLE
Not able to create temporary tables

### ISSUE THREAD

**Issue by Hloni-Mohohlo** [TeamSQL/desktop-app#124]
OS: Darwin x64 16.6.0
VERSION: 0.9.97
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

When you insert data into a temporary table, then try to select from the temporary table.

Example: select * into #t1 from {tableName}
                  ***7 Rows Affected
      select * from #t1 
                Invalid object name '#t1'

**Comment by erenbaydemir** [comment]
Hi @Hloni-Mohohlo , which database engine are you using?

**Comment by abacigil** [comment]
If it's Redshift, we couldn't replicate the issue, please give us more detail.
