### ISSUE TITLE
csv Export function

### ISSUE THREAD

**Issue by DarrenMAllen** [TeamSQL/desktop-app#128]
I can't seem to find a way to export data in any format. This is a key dependency for my department.

**Comment by abacigil** [comment]
Hi there, please check these tutorials:

Export as CSV, JSON, or tab separated: 
- https://blog.teamsql.io/exporting-data-using-teamsql-da7131517bb8

Share result set via link:
- https://blog.teamsql.io/sharing-data-via-hyperlink-27356ebee692
