### ISSUE TITLE
[Feature Request] RPM Package (Fedora)

### ISSUE THREAD

**Issue by vzool** [TeamSQL/desktop-app#129]
Hi,

Is there any plan to support TeamSQL for Linux in RPM Package format?

Thanks

**Comment by MichaelRBond** [comment]
I would like to see this as well. Or, at the very least, a generic linux download instead of a .deb

**Comment by KinG-InFeT** [comment]
+1

**Comment by badarotti** [comment]
+1

**Comment by vzool** [comment]
@murteza Would you please consider `RPM` for **OpenSUSE** too?

Thanks

**Comment by murteza** [comment]
Hi @vzool @MichaelRBond @specialtactics @KinG-InFeT @badarotti , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by vzool** [comment]
@murteza I can run it by this command:

```shell
➜  chmod +x TeamSQL-4.0.270-x86_64.AppImage
➜  ./TeamSQL-4.0.270-x86_64.AppImage
```

So, I noticed the icon appeared in Gnome start menu.
But, after I delete the downloaded file then anything related to the App just disappear.
Is this completely a portable version?

**Comment by abacigil** [comment]
Hi @vzool ,

You must keep .AppImage file, it's the executable. If you delete it, it means app is not exist.

**Comment by HPODEV** [comment]
+1
