### ISSUE TITLE
Invitation doesn't work. 

### ISSUE THREAD

**Issue by utkusubakan** [TeamSQL/desktop-app#134]
OS: Darwin x64 16.0.0
VERSION: 1.0.108
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

On teams&management window, inviting a team member doesn't work. After confirmation popup, no email received by team member. Also there is no record on pending invitations.

**Comment by abacigil** [comment]
It was a backend issue, and now it's fixed.

Thanks @utkusubakan
