### ISSUE TITLE
Show Connection problem

### ISSUE THREAD

**Issue by zahedul** [TeamSQL/desktop-app#135]
<img width="1280" alt="screen shot 2017-07-13 at 1 43 44 am" src="https://user-images.githubusercontent.com/1929044/28136766-be492c14-676c-11e7-9903-f1ce9e2b2471.png">
I couldn't login. my internet connection is ok but couldn't login in team sql

**Comment by erenbaydemir** [comment]
Hi there! Are you working behind a firewall or do you need to use a proxy to connect to the web?
