### ISSUE TITLE
Snowflake DB support?

### ISSUE THREAD

**Issue by Vfisa** [TeamSQL/desktop-app#138]
Hi, would you consider adding Snowflake DB support?

**Comment by abacigil** [comment]
Hi @Vfisa 

Currently we don't support it but it's in our potential features list.

Thanks.

**Comment by Vfisa** [comment]
Hi, Any update on this? Many thanks!

**Comment by franckatwag** [comment]
SnowFlake is becoming a serious DW contender, and major companies are switching away from Redshift for SnowFlake. I would seriously look into it.

**Comment by TBusen** [comment]
+1

**Comment by tcpaddock** [comment]
+1

**Comment by asherkinyon** [comment]
+1

**Comment by briamkin** [comment]
+1
