### ISSUE TITLE
White Background for data grid problematic in full black ui

### ISSUE THREAD

**Issue by ayanb1991** [TeamSQL/desktop-app#141]
Hi, I am using TeamSQL for quiet a time. It's fantastic. I use dark themes for most of my workspaces. In case of TeamSQL it is also a dark ui, but the data grid is white and it is tough to stare. (And I think it's not matching to the whole ui at all). It will be great if an option to make data grid adopt the black interface is given.

Thanks.

**Comment by abacigil** [comment]
Hi @ayanb1991 , 

It's on our roadmap, please see: https://github.com/TeamSQL/desktop-app/issues/67

and please check : https://github.com/TeamSQL/desktop-app/projects/3

Thanks for the feedback!
