### ISSUE TITLE
Performance issues on macOS

### ISSUE THREAD

**Issue by tansudasli** [TeamSQL/desktop-app#143]
Amazon RDS de, t1micro postgre açtım. Sample bir db create etmek için (https://community.embarcadero.com/article/articles-database/1076-top-3-sample-databases-for-postgresql daki sports db scripti) çalıştırdım.

Ve teamsql bembeyaz bir ekran. kitlenip bayılıp kendinden geçiyor.
[sportsdb_sample_postgresql.zip](https://github.com/TeamSQL/desktop-app/files/1196431/sportsdb_sample_postgresql.zip)

**Comment by erenbaydemir** [comment]
Performance problems when running import scripts for the sample SportsDB (https://community.embarcadero.com/article/articles-database/1076-top-3-sample-databases-for-postgresql).
