### ISSUE TITLE
Add running indicator to tabs on the left panel.

### ISSUE THREAD

**Issue by gaganis** [TeamSQL/desktop-app#145]
When a long running query is executed, the execute button provides feedback with a spinning icon.

While the query is running we can switch and work on another tab. It would be nice when we are working on a different tab, the left panel would also include a spinning feedback that a query is running inside it.

If that is the case when working on a different tab we can see that a query in another tab has finished its execution and go back and see it's results.

Thanks!
Giorgos

**Comment by erenbaydemir** [comment]
Hi @gaganis ,

We actually do have an indicator for that. You can see an screenshot below. Do you have that indicator in your client or is it missing for you? 

Cheers, 

![aug-25-2017 14-17-47](https://user-images.githubusercontent.com/688276/29712004-533edc92-89a0-11e7-8145-622dc3792be3.gif)

**Comment by gaganis** [comment]
Hello @erenbaydemir,

Thank you for your reply, not that I see your screenshot, I have tried again and I have found out that the spinner next to the tab name in explored actually comes up when I run my query, but then it immediately disappears(it spins just enough time to see it). The query continues to execute and the 'execute' button spinner also continues to spin.

Thanks
Giorgos
