### ISSUE TITLE
macOS Sierra Desktop App: application will not render after upgrade to v1.2.113

### ISSUE THREAD

**Issue by frank-dall** [TeamSQL/desktop-app#146]
I have taken the normal troubleshooting steps of uninstalling/reinstalling and restarting with no luck. The issue seemed to have started occurring after upgrading to TeamSQL v1.2.113. Any other ideas? Screenshot attached.

![screen shot 2017-08-16 at 9 09 52 am](https://user-images.githubusercontent.com/8002211/29373534-6eed6efc-8263-11e7-9e91-57195227ef07.png)

macOS Sierra 10.12.6 (16G29)

OS: Darwin x64 16.7.0
VERSION: 1.2.113
---------------
Database Type: N/A
How can this issue be reproduced?
On launch, the Desktop application does not render

**Comment by abacigil** [comment]
Hi there, please see: #120

**Comment by frank-dall** [comment]
Whoops, should have checked closed issues first. Worked perfectly, thanks @abacigil !
