### ISSUE TITLE
Multi selection, dont done query. 

### ISSUE THREAD

**Issue by aykutkardas** [TeamSQL/desktop-app#149]
https://giphy.com/gifs/xUNemUEEGYvdCz7Qly/fullscreen

**Comment by erenbaydemir** [comment]
Hi, could you please provide more details about the case?

**Comment by erenbaydemir** [comment]
Thank you @aykutkardas . This fix will be included in v1.4 update.

**Comment by abacigil** [comment]
Fixed on v1.4.122
