### ISSUE TITLE
Passwords stored as plain text

### ISSUE THREAD

**Issue by furtive** [TeamSQL/desktop-app#150]
On macOS both connections.json and credentials.json contain password fields with the data stored in plain text.  Both files are located under ~/Library/Application Support/TeamSQL/App Cache/users/{unique user id}/

Seems to me this is a serious issue.

**Comment by huyphams** [comment]
Wow I didn't know that 😨

**Comment by aykutkardas** [comment]
Valid within Windows. It's a worrying situation. :fearful:

**Comment by abacigil** [comment]
Fixed on v1.4.122
