### ISSUE TITLE
Redis HGETALL does not work

### ISSUE THREAD

**Issue by urossmolnik** [TeamSQL/desktop-app#154]
When executing `HGETALL` output window stuck at Running...  
No Results are shown.

If I execute same command in redis-cli I get results.

TeamSQL Version 1.3.117 (1.3.117.117)

**Comment by abacigil** [comment]
Hi @urossmolnik 
Is it happening all the time for the same hash?

**Comment by urossmolnik** [comment]
Yes, I am able to reproduce it every time.

    hset asdf asdf1 1
    hset asdf asdf2 2
    hgetall asdf

Last command (`hgetall`) is stucked at Running.

**Comment by urossmolnik** [comment]
Just a note.
`HGETALL` works, `hgetall` doesn't.

**Comment by abacigil** [comment]
We will fix it asap

**Comment by abacigil** [comment]
Hi @urossmolnik ,

We fixed the bug, and released a hot fix for that, update will be available in a day, or you can download fixed version from our web site. https://teamsql.io/download
