### ISSUE TITLE
New database not shown in explorer even after refresh

### ISSUE THREAD

**Issue by CatalinManolescu** [TeamSQL/desktop-app#172]
OS: Windows_NT x64 10.0.15063
VERSION: 2.0.125
---------------
Database Type: MySQL
How can this issue be reproduced?

1. Connect to a MySQL server using the 'mysql' table 
2. Go to the 'File' menu and select the 'New Query' option from 'Active Connection' group.
3. In the query window type 'create database somedbname;' 
4. Right click on the connected server (from 'Explorer') and click on the 'refresh' action

Actual result:
The newly created database is not shown.

**Comment by abacigil** [comment]
We are currently working on JDBC support and this will be fixed with that release

JDBC Support: #180
