### ISSUE TITLE
TeamSQL always starts maximized on MacOS

### ISSUE THREAD

**Issue by cipsys** [TeamSQL/desktop-app#173]
TeamSQL always starts maximized on MacOS. 
Steps to reproduce:
1. start TeamSQL
2. TeamSQL starts maximized
3. resize the window to a smaller size
4. quit TeamSQL
5. restart TeamSQL
6. window is maximized.

Is there a way to make it start non maximized?

**Comment by a2nt** [comment]
The same issue at Linux

**Comment by i07** [comment]
And on windows, so a +1 here

**Comment by rlevas** [comment]
+1 to fix this.

**Comment by murteza** [comment]
Hi @cipsys @a2nt @i07 @rlevas , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
