### ISSUE TITLE
current_timestamp + NOW() functions are not working correctly. 

### ISSUE THREAD

**Issue by rohitsalim** [TeamSQL/desktop-app#175]
OS: Darwin x64 15.6.0
VERSION: 2.1.127
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

Here is the credentials for the database:
**Host**: datadriven.cb348prunfpg.us-east-2.rds.amazonaws.com
**Port**: 5432
**Username**: data_apprentice
**Password**: bec0mingDataDriv3n
**dbname**: postgres

The current_timestamp & NOW() functions do not work as expected. 

I have a table in this database called employees_employee which contains a date_joined column which is a Date field. 

I execute the following queries:
SELECT NOW() - date_joined FROM employees_employee;
SELECT current_timestamp - date_joined FROM employees_employee;

However, the answer being returned is NULL. This is incorrect and is not how these functions are supposed to work. 

That being said, the following query does work:
SELECT current_date - date_joined FROM employees_employee;

Based on process of elimination, I don't think the TEAMSQL engine is properly handling date math between current_timestamp and NOW() (Timestamp objects) and the date_joined field (a Date Field). 

If I were to execute this query on the command line, it does not return a NULL and hence that is how I am convinced that the behaviour followed on TeamSQL is not correct. 

Please let me know if you need more details.

**Comment by rohitsalim** [comment]
Is anyone looking to this issue?

**Comment by abacigil** [comment]
You shared your username, password and other private informations in public Github page. Please edit your question and remove those informations and change your username and password if you shared them by mistaken, if not please specify so we can use connection string to test your case.

As a note; in TeamSQL, we do not make any calculation or apply logic. Any query you run, goes to database server and we show returned data.

**Comment by ghostsprofile** [comment]
Looks like TeamSQL can't handle "interval" datatype at all.
Just checked:
`select '6784 second'::interval;`
returns null, but supposed is similar to
`select ('684991 second'::interval)::text;`

**Comment by abacigil** [comment]
Hi @rohitsalim 

It's fixed with latest release 3.1.184, please update your TeamSQL.

Thanks!
