### ISSUE TITLE
Table structure view does not work on second click

### ISSUE THREAD

**Issue by ashatp** [TeamSQL/desktop-app#176]
I am connected to postgreSQL. On clicking on table structure preview, the table is shown only on first click. Second time the view does not appear properly. I need to close and the open the app again to see it. But that works again for first click only.

First time
![image](https://user-images.githubusercontent.com/4597898/31327374-df0265ac-acdf-11e7-95ab-9812555a5f89.png)

Second time
![image](https://user-images.githubusercontent.com/4597898/31327386-fa8da9e4-acdf-11e7-86cf-9749a04ee344.png)

**Comment by erenbaydemir** [comment]
hi @ashatp , we're looking into this. Thanks for reporting this one.
