### ISSUE TITLE
Downloading 2.1.127 update, repeatedly 

### ISSUE THREAD

**Issue by wisesabre** [TeamSQL/desktop-app#177]
OS: Darwin x64 16.7.0
VERSION: 2.0.125
---------------
How can this issue be reproduced?

Update dialog pops up. I tried using download in background and after some time it popped again. Tried downloading in foreground - its annoying - the dialog never went away. 

Restarted app multiple times too.

Proxy server might also be blocking download URL.

**Comment by wisesabre** [comment]
![screen shot 2017-10-10 at 2 45 26 pm](https://user-images.githubusercontent.com/400207/31380076-bec5f3f4-adc9-11e7-804e-befd5957bf44.png)

**Comment by erenbaydemir** [comment]
Hi @wisesabre. We are looking into this. Do you have any other clue that might be helpful for reproducing the issue other than the Proxy one. It's probably about the proxy and something that we didn't handle for connections over proxy but it would be great if there are anything else that could be helpful.
