### ISSUE TITLE
Paste result as SQL INSERT/UPDATE

### ISSUE THREAD

**Issue by demuro1** [TeamSQL/desktop-app#178]
Add paste query results as an SQL INSERT or SQL UPDATE statement to command palette

in table user_info
the columns are
pid, first_name, last_name, date_of_birth , age

and a qry result is

1, Mike, Smith, 03-21-90, 27
39, Bob, Anderson, 04-11-79, 38

Currently if you right click a result:
 "Copy Cells As  > CSV" is an option.  

From the command palette you would have the option to paste as SQ INSERT or paste as SQL UPDATE 

the insert would create the following paste:

INSERT INTO user_info (first_name, last_name, date_of_birth , age) VALUES (Bob, Anderson, 04-11-79, 38);

the update would create the following paste:

UPDATE user_info SET first_name = 'Bob', last_name = 'Anderson', date_of_birth = '04-11-79' , age =  38 WHERE pid = 39 LIMIT 1;

**Comment by abacigil** [comment]
Hi there, we just made an extension for that and it'll be available in a few days.

<img width="881" alt="screen shot 2017-10-16 at 14 06 12" src="https://user-images.githubusercontent.com/759174/31609043-3e824f38-b27b-11e7-8b34-35aa423f85bc.png">

**Comment by abacigil** [comment]
It's available with the latest release v2.2.131 and also here: https://teamsql.io/extensions/sql-generator

**Comment by demuro1** [comment]
Thanks,
	I downloaded it on release day.  Awesome feature.

Jason
