### ISSUE TITLE
Repeated intellisense 

### ISSUE THREAD

**Issue by jping0929** [TeamSQL/desktop-app#179]
I'm using TeamSQL for Ubuntu. It appears that the system will show duplicated words for intellisense.
![screenshot from 2017-10-18 19-43-12](https://user-images.githubusercontent.com/30264958/31747786-d99ebda4-b43c-11e7-8e62-fe8bde97c2bd.png)

**Comment by erenbaydemir** [comment]
Thank you for reporting this. We identified and issue and are working on this.
