### ISSUE TITLE
JDBC Support

### ISSUE THREAD

**Issue by erenbaydemir** [TeamSQL/desktop-app#180]
We're working on adding JDBC support to TeamSQL as an alternative way of connecting to your servers.

**Comment by Catscratch** [comment]
Will it be possible to use any JDBC driver (e.g. for other databases that are not directly supported)?

**Comment by selcukkiziltug** [comment]
Hi @Catscratch , thank you for reaching out to us. Currently, JDBC driver support will be available in the next version of TeamSQL. Until then, you can give a try to the beta release of TeamSQL 4 at [https://teamsql.io/nightly](https://teamsql.io/nightly) which supports JDBC driver. Your feedback is important to us. We appreciate your feedback.

**Comment by Catscratch** [comment]
Thanks for your reply.

And where excactly may I configure a JDBC driver for e.g. SAPs MaxDB? I can only see common databases like MySQL, Postgres etc.

**Comment by erenbaydemir** [comment]
Hi @Catscratch , currently you can't use your own JDBC drivers in TeamSQL 4 Beta, we just switched existing drivers with JDBC ones. But we will add custom JDBC support very soon.

**Comment by nbarraille** [comment]
@erenbaydemir Any news on the custom JDBC support? Would love to be able to connect to AWS Athena through TeamSQL

**Comment by sj-plenty** [comment]
^^ I would be very interested in the feature as well!

**Comment by sj-plenty** [comment]
@barisozanguler @fatihdervisi  not sure why that happened
