### ISSUE TITLE
Support info, notice, warning(stderr) output channel for PostgreSQL plpgsql

### ISSUE THREAD

**Issue by ghostsprofile** [TeamSQL/desktop-app#185]
The only way to expose some information about processes within function and DO-block in postgresql is RAISE statement. Here is some demo (use psql or pgadmin3 for best experience):
`do $$ begin
raise info 'Started at %', now();
raise info ' Doing stuff...%', pg_sleep(2);
raise notice '% miracle', (random()=random())::text;
raise warning 'Finished at %', clock_timestamp(); end $$ `
Appearance of recent output 'on-line' or each second will be perfect, but showing output after finishing is good enough too.

**Comment by huffmd** [comment]
RAISE EXCEPTION is already handled elegantly. It just needs to support all levels of RAISE the same way (e.g. NOTICE, DEBUG, etc.). There may need to be improvement on the model to scroll through all of the output from the function.

**Comment by murteza** [comment]
Hi @ghostsprofile , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
