### ISSUE TITLE
The Drop Table command is placed dangerously on the table's context menu

### ISSUE THREAD

**Issue by philoushka** [TeamSQL/desktop-app#190]
![why2](https://user-images.githubusercontent.com/930731/33052457-cf4e83ba-ce23-11e7-99a4-498a3d0465f6.png)

This is a poorly placed command. It has no business being near and in between 2 commonly used actions on a table.

Mitigating factor: there's probably a confirmation dialog box that shows after it's clicked (as indicated by the ellipses).

This commands belongs somewhere else, and not in a high traffic area.

It's *too easy* for a user to trigger this destructive action by *mistake*.

![6a0120a85dcdae970b01310fd5f5e9970c-800wi](https://user-images.githubusercontent.com/930731/33052470-e22070f2-ce23-11e7-9e46-e8cf547f7c0c.png)

**Comment by erenbaydemir** [comment]
This is the best issue description I've ever seen in Github. :)

We moved Delete option to the button and this change will be included in our next release. 

Thanks a lot for reporting this.
