### ISSUE TITLE
Comment in query...it is possibile to ignore it?

### ISSUE THREAD

**Issue by samuelepretini** [TeamSQL/desktop-app#198]
In my query tab I have this instruction:
select count(*) from jobpostapplication as jpapp 
where 
--inner join jobpost as jopo on (jpapp.jpap_jopo_id=jopo.jopo_id)
jpapp.application_date > '2017-09-01'
and jpapp.application_date <= '2017-09-30'
;

if I execute this, Mysql return an error because there is the row:
--inner join jobpost as jopo on (jpapp.jpap_jopo_id=jopo.jopo_id)

but I don't want to execute the inner join.

How I can comment a row, without move it from my query?

OS: Darwin x64 17.2.0
VERSION: 2.4.143
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

**Comment by erenbaydemir** [comment]
This should be caused by the missing space character after --. It should be working if you put a space between -- and "inner".

https://dev.mysql.com/doc/refman/5.7/en/ansi-diff-comments.html
