### ISSUE TITLE
Files saved under folder are not accessible

### ISSUE THREAD

**Issue by ChristopherBaldwin** [TeamSQL/desktop-app#199]
OS: Darwin x64 16.7.0
VERSION: 2.4.143
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

Save a file under a folder.  Then try to open it.  You can't.  Clicking on the folder shows a blank screen.

**Comment by abacigil** [comment]
Hi @ChristopherBaldwin 

Can you try yo update TeamSQL to the latest version? We have fixed some bugs which were affecting folder and files system.

Let me know if it still continues.
