### ISSUE TITLE
variable reports as null but is not null

### ISSUE THREAD

**Issue by demuro1** [TeamSQL/desktop-app#202]
OS: Darwin x64 17.2.0
VERSION: 2.4.143
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

SET @id := 2312198;
SET @store := 320;
SET @job := 'TASK0205574';
SELECT ifnull(@job,'why am I null') as 'JOB', concat(@store,',',@id) as 'PASTE for DB Updater', @store as 'STORE', @id as 'ID', concat('JD;',@job,';UPDATE progreso_production.disbursements SET store_id = ',@store,' WHERE id = ',@id,' LIMIT 1;') AS QUERY;

The first @job will show value "NULL" but will populate in the concat.  
The value is not null because the IFNULL function does not return "why am I null" and it populates a value in the second concat

<img width="1016" alt="screen shot 2017-12-18 at 2 19 32 pm" src="https://user-images.githubusercontent.com/32468854/34130910-800dfcf4-e3fe-11e7-9f85-698f18677385.png">

**Comment by abacigil** [comment]
Hi @demuro1 

We just released a hot fix update now, please update to the latest version (v2.5.155).
