### ISSUE TITLE
SSH Tunnel Connection failed!

### ISSUE THREAD

**Issue by shsbd** [TeamSQL/desktop-app#211]
OS: Windows_NT x64 10.0.16299
VERSION: 3.0.167
---------------
Database Type: MySQL

How can this issue be reproduced?

While I try to add a database from an external source, it shows the error. Although, I have tested with another application and everything works correctly. I have correctly added the `Tunnel with IP, username and SSH Key file` but seems it does not work. Only the local database connects easy. But remote database went failed when trying to add.

![2018-02-17 13_48_11-teamsql](https://user-images.githubusercontent.com/12555542/36339168-40512210-13e9-11e8-949b-90ea6214745c.png)

**Comment by AaronKaa** [comment]
I have the same issue on macOS 10.13.3 - I cant get a single SSH host to work

**Comment by murteza** [comment]
Hi @AaronKaa @shsbd , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by shsbd** [comment]
@murteza Seriously? 6 months later you have replied the issue?

But thanks for the update.
