### ISSUE TITLE
Feature Request: On Premise or Private Cloud

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [TeamSQL/desktop-app#212]
Hi there,

your software looks very good but as with so many other software products, it seems you are only offering a cloud solution which is hosted by yourself.

How are you thinking about offering your software for installation on a private cloud environment? This would allow companies that don't want to store sensitive information in someone else cloud to still benefit from using your software.

**Comment by murteza** [comment]
Hi Thomas,

Actually, we have a private cloud solution. If you want, I will send you details.

**Comment by ThomasSchoenbeck** [comment]
Hi there,

thanks for the info. Unfortunately the company (in the banking industry) i am currently working for has to deal with a lot of regulations and compliance. If we can't run it ourselves (in our own company cloud), we can't use it. so sad.

**Comment by murteza** [comment]
Hi @ThomasSchoenbeck,

I understand what you need. We have that solution for companies like yours. You can run TeamSQL in your company private cloud. 

Thank you

**Comment by ThomasSchoenbeck** [comment]
Hi @murteza 

That sounds great. I would like to get more info on this.

**Comment by murteza** [comment]
Sure! So we can arrange a meeting over Skype. 
Have you any available time for this week?

**Comment by ThomasSchoenbeck** [comment]
Hi @murteza ,

this week might not be possible. Let me look something up for next week. Also we do not have Skype in here, so i need to find a way to use my private laptop.

Which timezone are you in? I am on CEST or GMT+2.

**Comment by murteza** [comment]
Hi @ThomasSchoenbeck 

Okay, we have some available time for next week. If you don't have Skype, we can arrange our meeting on a different platform. You can tell us the platform. Our timezone is GMT+3.

**Comment by Ph0xEn** [comment]
Hi @murteza,

what is the current solution to run TeamSQL in my own private cloud or completely without a cloud service?

Thank you very much!

**Comment by vinguan** [comment]
+1 for @Ph0xEn. It would be really cool, to pay for the software and save our queries in our own cloud service by our choice (OneDrive, GDrive, Dropbox, other...)

**Comment by ckizziar** [comment]
@murteza I too would like to find out about running TeamSQL in private cloud.
