### ISSUE TITLE
TeamSQL freezes entire computer on newest version

### ISSUE THREAD

**Issue by jacob-israel-turner** [TeamSQL/desktop-app#213]
The latest release of TeamSQL freezes my whole computer on Ubutnu 16.04.3

When it was updating it was fine for a while then froze my whole computer. I restarted my machine, and tried again. Same problem. So I uninstalled TeamSQL and reinstalled, thinking the update process was the issue. But as soon as I started up TeamSQL again, it froze my computer after loading the initial UI.

In the meantime, is there a way for me to install older versions of TeamSQL? I'd hate to download a new client for just a few days while this is fixed.

**Comment by abacigil** [comment]
Hi Jacob,

Can you try to delete all folders inside 'home/YOUR_USERNAME/.config/TeamSQL/AppCache/users/' ?

Thanks,

**Comment by jacob-israel-turner** [comment]
Thanks for responding @abacigil.  I deleted everything within that directory.  Unfortunately that did not solve the problem.

**Comment by jacob-israel-turner** [comment]
I've gone with sqlectron for the cross-platform support until this is resolved.  I'll keep an eye on this issue in case it's resolved soon.

**Comment by murteza** [comment]
Hi Jacob,

Are you still having the same problem?

**Comment by murteza** [comment]
Hi @jacob-israel-turner 

Are you still having the same problem?
