### ISSUE TITLE
[UI] Interface is monstrous, non-friendly and without edit-in-line features 

### ISSUE THREAD

**Issue by a2nt** [TeamSQL/desktop-app#214]
I was seeking for an alternative to Sequel Pro, but still haven't found it.

Here's a list of UI issues at TeamSQL:

+ No indication that results panel can be resized and if it was resized u will need to resize it every time u make a query. 
![screenshot from 2018-02-26 21-20-25](https://user-images.githubusercontent.com/672794/36675242-5c172896-1b00-11e8-9770-2af28a92fc12.png)

+ Unable to edit rows and fields inline. It would be nice to edit it in table's row by double click
![screenshot from 2018-02-26 21-22-48](https://user-images.githubusercontent.com/672794/36675365-a2a4e758-1b00-11e8-8ece-8936b7fc6bb6.png)

+ Tabs at the left? Really? Also this panel has too big margins and paddings which makes it hard to browse long table lists and takes 30% of my screen.  
![screenshot from 2018-02-26 21-24-52](https://user-images.githubusercontent.com/672794/36675483-fd41f76e-1b00-11e8-9321-f4cb3ece4a83.png)

+ Dunno, what is this, but looks like a bug:
![screenshot from 2018-02-26 21-28-25](https://user-images.githubusercontent.com/672794/36675608-66fc9830-1b01-11e8-9851-c9c953cb40eb.png)

+ I'd like to be able to hide SQL query window if I don't need it
![screenshot from 2018-02-26 21-29-52](https://user-images.githubusercontent.com/672794/36675687-9f567fc0-1b01-11e8-81e4-3cf24ffb0756.png)

+ Every click on the table opens new tab
![screenshot from 2018-02-26 21-32-31](https://user-images.githubusercontent.com/672794/36675797-e7406044-1b01-11e8-982c-ca61b9312415.png)

+ Connection to DB is not persistent and every query makes TeamSQL to reconnect SSH>MySQL which makes it extremely slow

+ Interface is dark, but pop-up windows are light.
![screenshot from 2018-02-26 21-36-08](https://user-images.githubusercontent.com/672794/36676036-8375a7ee-1b02-11e8-8f62-cedce4569f8d.png)

+ Help > Check for updates doesn't have any idication

+ Nothing happens when I click buttons here:
![screenshot from 2018-02-26 21-39-00](https://user-images.githubusercontent.com/672794/36676165-d62f756e-1b02-11e8-93ad-d0f6a64dae38.png)

+ Ctrl + - makes font smaller, but it isn't intuitive to make font bigger on Shift + Ctrl + = Anyway why would u possible make font smaller when toolbars and buttons all around UI takes the biggest part of your screen.

+ That's a bug:
![screenshot from 2018-02-26 21-43-18](https://user-images.githubusercontent.com/672794/36676372-6fb9ca40-1b03-11e8-8193-828402c34225.png)

P.S. Hopefully TeamSQL will be better latter. I'd like to have useful dark themed SQL GUI to save my eyes during night. Also that will be great to have smaller UI and autohide panel options

**Comment by abacigil** [comment]
Please update to 3.2.187 version, inline editing feature is now available.

Thanks,

**Comment by a2nt** [comment]
Thanks, works great

**Comment by markfsuk** [comment]
I whole heatedly agree that persistent connections would be much nicer. It's a fair time overhead to reconnect for every single query.
