### ISSUE TITLE
[UI] Improvements > explorer tab

### ISSUE THREAD

**Issue by a2nt** [TeamSQL/desktop-app#218]
+ If there's no active connection explorer tab shall be shown so user will be able to select a server to connect or at least servers shall be listed at the content area.

+ New connection setup is too slow cuz of loading available databases

+ New connection setup shouldn't require host name. There's a placeholder 127.0.0.1 so if I don't enter anything 127.0.0.1 shall be used by default.
![screenshot from 2018-03-27 16-38-12](https://user-images.githubusercontent.com/672794/37960555-1aee9236-31e0-11e8-9c40-3a313b5e9143.png)

+ Explorer Navigation: Current connection shall be fixed to top (only DB's of this connection shall be shown).
When DB is selected current DB shall be fixed to top (only tables of this DB shall be shown).

It shall have back link to go to upper level (or go on click to the header) with DB list or connection list.
For an example active connection at the screenshot shall be a header of explorer area:
![screenshot from 2018-03-27 16-48-05](https://user-images.githubusercontent.com/672794/37960607-3e04aed6-31e0-11e8-972c-88c544e5704d.png)

Right now when u have a lot of connections and a lot of databases + a lot of tables u have to spend a lot of time scrolling around.

+ BUG: after setting up new connection table names became unclickable.

+ Selecting an item at the header dropdowns doesn't work and reloads popup lists every time which makes it slow.
![screenshot from 2018-03-27 16-55-48](https://user-images.githubusercontent.com/672794/37960545-128401ee-31e0-11e8-8427-10b7ac80f295.png)

I think it will be better to cache this lists and make an update button to update it. It shall be the same list at the explorer area.

**Comment by murteza** [comment]
Hi @a2nt , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
