### ISSUE TITLE
[UI] Editable table rows improvement

### ISSUE THREAD

**Issue by a2nt** [TeamSQL/desktop-app#219]
Need to highlight table row on hover (color #1), currently selected row (color #2), currently selected field (color #3), changed field before applying changes (color #4)

Right now only specific selected field is highlighted:
![screenshot from 2018-03-28 20-08-31](https://user-images.githubusercontent.com/672794/38030899-1b1048ec-32c4-11e8-93f8-de6142c21abc.png)

**Comment by murteza** [comment]
Hi @a2nt ,

We’ll fix this known issue with the next version. 
So, please stay tuned!
