### ISSUE TITLE
SSH connection test, does not work.

### ISSUE THREAD

**Issue by jerfeson** [TeamSQL/desktop-app#221]
OS: Windows_NT x64 10.0.16299
VERSION: 3.2.187
---------------
Database Type:  Mysql
How can this issue be reproduced? 

Have a vagrant environment
Click Add Connection, fill in the fields, choose to use an SSH tunnel, fill in the fields except the password, use a private key, and click Test Connection.

Fields;
Connection name: localhost
host: 127.0.0.1
port: 3306

user: root
pass: root

ssh
host: 127.0.0.1
post: 2222
user: ubuntu
private key file;

If I save the connection without testing, it works normally.
I do not know if this happens only with vagrant

**Comment by AALMA** [comment]
Experienced the same issue when testing a new mysql connection that uses SSH tunneling 

![teamsql_error](https://user-images.githubusercontent.com/5289607/38372679-67841fec-38bd-11e8-98e5-cf66a71cf5bc.png)

**Comment by zanvd** [comment]
Same behaviour on Linux Mint 18.3 with vagrant running Ubuntu.

The connection hangs when testing a connection and when trying to connect.

**Comment by zanvd** [comment]
Hi,
I'm wondering whether this has any roadmap since it's been in the _Ready for the Next Release_ status for over a month now.
Regards,
Žan

**Comment by murteza** [comment]
Hi @jerfeson @AALMA @zanvd , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by zanvd** [comment]
I have tried out the latest nightly build 4.0.270 and when trying to establish a connection I get the following error:
`Java server not working`

OS: Linux Mint 18.3
Kernel: 4.15.0-30-generic
Java: 1.8.0
VirtualBox: 5.2.16
Vagrant: 2.1.2
MySQL: 5.7.23

**Comment by murteza** [comment]
Hi @zanvd 

Let me check with the team and get back to you with more detailed information.

**Comment by mobaraksaid** [comment]
I'm getting the same error on the latest nightly build 4.0.307

**Comment by murteza** [comment]
#372
