### ISSUE TITLE
Transpose Result Set Table

### ISSUE THREAD

**Issue by JamesHamiltonDotCodes** [TeamSQL/desktop-app#225]
Feature Request

Allowing the user to transpose the result set table can be a very helpful feature when analyzing query results.

This is a link for an example of how this works in Excel: https://www.ablebits.com/office-addins-blog/2014/03/06/transpose-excel-rows-columns/

**Comment by murteza** [comment]
Hi @JamesHamiltonDotCodes ,

Thank you for reaching out to us. This is a nice to have feature. Let me check with the team and get back to you if we will consider adding to our roadmap.
So, please stay tuned!
