### ISSUE TITLE
Can only explore first db in postgres (9.2) connection

### ISSUE THREAD

**Issue by johnpaularthur** [TeamSQL/desktop-app#226]
We are currently using postgres 9.2 across our organization.   We can connect and query the databases, but the left side database explorer will only show the objects in the first database on the server.   Even choosing "Show only default database" will not show the objects in that default database.   In the attached screens, you can see we are connecting to the "cardholder" db, but only the "archive" db is expanding to show objects.

![edit_connection](https://user-images.githubusercontent.com/7483101/38202907-09b1cbdc-3663-11e8-89f5-f5dd4d519288.png)

![connection_tree](https://user-images.githubusercontent.com/7483101/38202912-0cf711e4-3663-11e8-820b-a56dfdb677ec.png)

**Comment by johnpaularthur** [comment]
Forgot to note details of app.  I'm on Linux (linux mint 18.3), but saw the same issue some time back on Mac.   I'm using teamsql v3.2.190.

**Comment by paguii** [comment]
Hello, i'm having the same issues today.

My OS:
Ubuntu 16.04 LTS

My version of postgres:
PostgreSQL 9.3.19 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

![captura de tela de 2018-04-09 10-45-32](https://user-images.githubusercontent.com/18687395/38501417-5a2c8ed2-3be3-11e8-891f-89282b055696.png)
