### ISSUE TITLE
Results gridview context menu missing

### ISSUE THREAD

**Issue by zkemppel** [TeamSQL/desktop-app#229]
After upgrading to 3.2.195, the right click context menu is completely missing from the results gridview.

**Comment by zkemppel** [comment]
First 2 things I tried.

**Comment by abacigil** [comment]
Okay, sorry forgot to say also;

Can you try to delete folders in the path below and restart it again?

Folder: /Users/YOUR_USER_NAME/Library/Application Support/TeamSQL/

**Comment by zkemppel** [comment]
That did it, thank you.
