### ISSUE TITLE
Unable to load some tables on some MySQL db

### ISSUE THREAD

**Issue by kielsoft** [TeamSQL/desktop-app#23]
OS: Darwin x64 16.1.0
VERSION: 0.9.45
---------------
Database Type: MySQL
TeamSQL not loading some tables in some of my db, just showing `undefined`.

TeamSQL view
![teamsql 2017-02-24 12-46-32](https://cloud.githubusercontent.com/assets/3008599/23302650/d261d560-fa8f-11e6-9c7e-7556ece6d66b.png)

SequelPro view
![mine newmed 2017-02-24 12-47-41](https://cloud.githubusercontent.com/assets/3008599/23302656/dac4d720-fa8f-11e6-82d3-97adcef597e7.png)

**Comment by abacigil** [comment]
Hi, what is your MySQL server version?

**Comment by kielsoft** [comment]
MySQL 5.7.15

**Comment by abacigil** [comment]
We've found the bug about upper-case letters in database names in MySQL, next release ( this week ) will cover the fix for this issue.

Thanks a lot!

**Comment by kielsoft** [comment]
you are welcome
