### ISSUE TITLE
NPM error when using teamsql-cli to create an extension project

### ISSUE THREAD

**Issue by zkemppel** [TeamSQL/desktop-app#230]
Get the following error after using `teamsql-cli create` then going into the new project folder and running `npm install`.

npm ERR! code E404
npm ERR! 404 Not Found: @ teamsqlio/ts-data-layer-core@1.0.18

**Comment by abacigil** [comment]
Hi @zkemppel 

Please update teamsql-cli using

`npm install @teamsqlio/teamsql-cli`

Latests teamsql-cli version should be 1.2.2

After you install the new version, try to create `teamsql-cli create` and choose one of the extension templates. Please also check version of ts-extension-sdk in package.json of generated extension template, it should be 0.4.5 or later.

Thanks,
