### ISSUE TITLE
Account Management and Support Links Broken

### ISSUE THREAD

**Issue by GeorgeMSchaffer** [TeamSQL/desktop-app#231]
This belongs in the support portal not here but since those are broken, I have no other recourse,   Like most companies, mine requires expense reports.  However when i click on the links either in the contextual menu on the bottom right or bottom left.  Then I tried to place a support ticket in the correct place. However, NONE OF THE LINKS WORK on the current versions of Chrome and Mac on High Sierra.

**Comment by murteza** [comment]
Hi @GeorgeMSchaffer 

Can you send an email to billing@teamsql.io?

Thank you.

**Comment by GeorgeMSchaffer** [comment]
Thanks!  I am not sure if the bug is on the website or the client. Please feel free to close depening on that.
