### ISSUE TITLE
[feature] shortcut to execute query under the cursor

### ISSUE THREAD

**Issue by anxolerd** [TeamSQL/desktop-app#24]
It would be great to have a convenient keyboard shortcut to execute query which is under the cursor now.
It is not very convenient to put hands away from keyboard and use mouse to execute a single query.

Currently the flow is:
- type a query
- move a hand away from keyboard
- put a hand on a mouse
- move mouse to the execute button
- click it

The desired flow is the following
- type a query
- hit a shortcut (i.e. Ctrl + Enter)

This, though would make a logic (for you) more complex, as you'll need to determine the query which is under the cursor, hence I propose the following:

1. Implement executing all queries by pressing a shortcut
2. When you will have enough time and resources implement executing a single query in a tab by pressing another shortcut

**Comment by abacigil** [comment]
Hi, you can use CMD+R on Mac or CTRL+R on Windows/Linux, also if you make a selection part of a query and call this shortcut or click on "Execute" button , it will only execute selected part.

We'll be making shortcut list more clear.
