### ISSUE TITLE
[Feature Request] Add option to disable auto-upgrade/download

### ISSUE THREAD

**Issue by jonjonw** [TeamSQL/desktop-app#251]
I install TeamSQL thorough a package manager and auto-updates fail. The program is quite aggressive about upgrade notifications. It would be nice to have an option somewhere to turn off auto-updates and to be able to close the out-of-date notification once the program has loaded.

**Comment by MikePryn** [comment]
:+1:

**Comment by abacigil** [comment]
Hi @jonjonw 

Official TeamSQL is only provided by teamsql.io, and we do not think to add something like disabling auto-update. 

Since you're installing TeamSQL via a package manager ( Arch Linux? ) you may have errors.

**Comment by SparK-Cruz** [comment]
Pop ups and auto-download is what really really sucks for usability, not only for package manager users but for everyone. What are you microsoft?

**Comment by richarddewit** [comment]
@abacigil can you at least make the notifications less aggressive and in your face? I update whenever I feel like it, not in the middle of a query. 

And the option to disable checking for updates automatically has my preference too. A lot of applications have this option. It's the only downside for me so far.

Installing TeamSQL via a package manager doesn't bring errors, the auto-update does. It invalidates the "current installed version" for the package manager.

**Comment by abacigil** [comment]
Hi guys,

We are going to release TeamSQL 4.0 (in a month) and TeamSQL for Linux will be an AppImage file, so you won't need to install TeamSQL via a package manager anymore.

We'll consider your feedbacks for TeamSQL 4.0.

Thanks,

**Comment by richarddewit** [comment]
@abacigil Good to hear :) exited to see the new version.

Nevertheless, Arch (and Arch-based) Linux users will always prefer installing software via package manager, so it **will** end up on AUR anyway. So I really hope the "Disable auto-update" checkbox will be present in version 4.0. It doesn't have to be turned off by default, you can even make it hard to find :see_no_evil:

Keep up the good work, it's a really nifty tool.

**Comment by Mattshiva** [comment]
AppImage does not connect . JDBC drivers error. Probably an arch issue. I fail to solve that.  

Would be cool however to disable popup update messages.
