### ISSUE TITLE
[Feature request] Add 'script <entity> as'

### ISSUE THREAD

**Issue by Alturil** [TeamSQL/desktop-app#252]
I found that very handy in SSMS; you can right click on an entity and select the option 'Script as...', which will prompt several options such as CREATE or ALTER. It doesn't matter which one of these, it would be great to have a way to get a scripted form of an entity so that you can see how it works, alter some parts or create a similar one.

**Comment by murteza** [comment]
Hi @Alturil ,

Thank you for reaching out to us. We will add your feature request to our roadmap. 

Meantime you try our "SQL Generator" extension.

![screen shot 2018-08-08 at 17 22 23](https://user-images.githubusercontent.com/1109510/43843321-ee1b3304-9b2f-11e8-9ecc-a951b43b983e.png)

How to download : 

1. Click the extension tab on the left side.
2. Search SQL Generator
3. Click to install button.
