### ISSUE TITLE
Stuck at 15-30 seconds after run query

### ISSUE THREAD

**Issue by eusokolov** [TeamSQL/desktop-app#256]
OS: Darwin x64 17.5.0
VERSION: 3.3.201
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?
Run query (I use simple table name instead of 'databasename'.'name') then it stucks for 15-30 seconds then I see that windows with "analysis of dangerous operations failure" and click "Execute" - after that query works fine.

**Comment by jeannei** [comment]
Same issue on macOS Sierra 10.12.6:
#### TeamSQL VERSION: 3.3.201

Database Type: MySQL
Steps to reproduce: Run a select query against any table

**Comment by nmfair** [comment]
Same on Windows 7 (64-bit), TeamSQL 3.3.201. I last used TeamSQL on Wednesday and don't think this was occurring then.

**Comment by abacigil** [comment]
Hi there,

We've fixed it, it was a backend issue.

Thanks,
