### ISSUE TITLE
Infinite refresh loop after Creating Stored Procedures on MYSQL database

### ISSUE THREAD

**Issue by 5PK** [TeamSQL/desktop-app#258]
I'm trying to view the Stored Procedures I've created on a MYSQL database. After running 

`SHOW PROCEDURE STATUS`

I can see my procedures exist, but when I refresh the db on the explorer, it continuously refreshes without showing me my new Procedures.

**Comment by abacigil** [comment]
Can you reproduce it? It looks like a connection problem.

Thanks
