### ISSUE TITLE
invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by clarking** [TeamSQL/desktop-app#259]
when i click in a table of my database in the side panel, it opens a new window but shows an error in results table.

- ubuntu 16.04 x64 
-kernel 4.13.0-39-generic #44~16.04.1-Ubuntu 
- database Postgres 10 in localhost
-query : SELECT * FROM "public"."_g_operators" LIMIT 200;
-error:  invalid byte sequence for encoding "UTF8": 0xed 0x61 0x20

**Comment by fatihdervisi** [comment]
Hi @clarking , If you need to store UTF8 data in your database, you need a database that accepts UTF8. Can you check your database encoding please, you can check the encoding with this query : 'SELECT * FROM pg_database'.

**Comment by clarking** [comment]
Hi, the databases that i'm using are all encoded with "es_MX.ISO8859-15", the output of the query you suggested is the following:

datname = 'postgres',
datdba = 10,
encoding = 0,
datcollate = 'es_MX.ISO8859-15',
datctype = 'es_MX.ISO8859-15',
datistemplate = 0,
datallowcolumn = true,
dataconnlimit = -1,
datalastsysoid = 13,274,
datafrozenxid = 548,
datminmxid = 1,
dattablespace = 1663,
datacl = Null

thanks for your support.
