### ISSUE TITLE
CSV Export table corrupts characters

### ISSUE THREAD

**Issue by ugurgokdere** [TeamSQL/desktop-app#26]
İstanbul is exported in a corrupted way. 

26938,Ä°stanbul,2017-02-03

**Comment by abacigil** [comment]
Hi Ugur,

CSV export feature writes to file as UTF-8 and we see output file's encoding and data are correct.

Which application are you using to open that file? If you're using Excel and import that CSV file to your sheet, it asks encoding in Import screen. By default it's not UTF-8.

Screenshots : 
![screen shot 2017-03-01 at 10 43 55](https://cloud.githubusercontent.com/assets/759174/23450428/d36876d0-fe63-11e6-9a57-c5777952c1a2.png)

After selection UTF-8 : 

![screen shot 2017-03-01 at 10 44 08](https://cloud.githubusercontent.com/assets/759174/23450434/d93545f2-fe63-11e6-808e-6c2a8ccdd778.png)
