### ISSUE TITLE
Option to disable Confirmation prompt

### ISSUE THREAD

**Issue by thebep** [TeamSQL/desktop-app#261]
Issue #28 asked for a confirmation prompt to be added for production environments, but it seems this prompt is also active for non-production environments. It would be nice if there was an option in the app preferences to disable this prompt

**Comment by murteza** [comment]
Hi @thebep 

You change your Query Sense settings in Preferences.

![image](https://user-images.githubusercontent.com/1109510/39983670-16305f80-5761-11e8-893d-d27fd1d4ad8b.png)

**Comment by thebep** [comment]
TeamSQL v3.3.203, MacOS 10.13.4

Even with QuerySense turned off, I still get a confirmation prompt on a non prod DB. 
<img width="1371" alt="screen shot 2018-05-14 at 4 24 51 pm" src="https://user-images.githubusercontent.com/4032784/40021632-64295ac0-5793-11e8-822a-409d52c39806.png">

**Comment by murteza** [comment]
Hi @thebep 

For now, we don't have an option for that.
If you edit or add a new row on your table (using data grid) it always asks which queries to be executed. 

We will add to our roadmap your feature request.

Thank you for your feedback.
