### ISSUE TITLE
Disable timed update check and remove "update available" bottom bar

### ISSUE THREAD

**Issue by null4bl3** [TeamSQL/desktop-app#267]
Hi guys.

There really needs to be an option to disable the constant update checks and at least an option to dismiss the "update available" bottom notification. If the application is installed using a package manager on linux, it is not possible to update using the update functionality in TeamSQL. And aggressively notifying me of an update every 10 minutes or so, does not change that fact. There could be a lot of reason why a user would not wish to update the very second a update is available, and those reasons would not change because of the application aggressively notifying the user of an available update. 

I really want to switch over to TeamSQL but the windows 10 like aggressive update nagging accompanied by random focus stealing popups is kind of a deal breaker.

**Comment by Bigsy** [comment]
+1 I use the TeamSQL AUR package (I suspect quite a few do) and there's always lag from the maintainer to update, pretty annoying to be nagged constantly in this situation. Thanks for the great software btw.

**Comment by MikePryn** [comment]
+1, auto-update "feature" breaks all usability, strange decision to not allow users to disable this feature

**Comment by Bigsy** [comment]
To add, if it's deemed it can't be turned off could you at least make it less annoying? Like get rid of the popup even if you keep the stuff at the bottom?

1. The popup steals focus even if teamsql is minimised, I could be writing an email and realised I just typed a sentence or two which is now lost as the popup stole focus moments before.

2. It just keeps pumping out the popups even if one is already there, everytime I come to the app I seem to have to wade through closing multiple ones popups.

**Comment by null4bl3** [comment]
Great job fixing this guys. Thanks

**Comment by SparK-Cruz** [comment]
Still not fixed
