### ISSUE TITLE
Charts can't be rendered when there is a null in text field

### ISSUE THREAD

**Issue by twelve-twelve** [TeamSQL/desktop-app#270]
OS: Windows_NT x64 10.0.17134
VERSION: 3.3.203
---------------
Database Type: mysql 5.1
How can this issue be reproduced?
create a table with a varchar column; ensure 1 row is null; execute a group by the varchar column; attempt to chart sql results

**Comment by abacigil** [comment]
Hi @twelve-twelve 

It should work now, we've fixed the issue. It will show an error if there is a NULL value in the result set. You can try to add a filter and ignore NULL values 

![screen shot 2018-05-25 at 12 38 37](https://user-images.githubusercontent.com/759174/40537826-9b863712-6018-11e8-9fc1-840eeb7cf0e3.png)
