### ISSUE TITLE
There are no tables in this database

### ISSUE THREAD

**Issue by blaasvaer** [TeamSQL/desktop-app#272]
Now, why am I getting this?

I connect to localhost, see my DB, click the 'public' item, click the table tab ... and then this depressing message.

Now, I would expect this to be a tool to actually help me get an overview of the content of any given postgresql database, but here I am typing issues on github.

And who came up with the idea, that this would be a great interface for DB administration? It's a disastrous 'modern web UI' that makes absolutely no sense in the context of DB administration.

**Comment by abacigil** [comment]
Hi @blaasvaer 

Which PostgreSQL version is it?

Thanks

**Comment by murteza** [comment]
Hi @blaasvaer ,

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
