### ISSUE TITLE
Apply functionality  not scape reserved keyword database

### ISSUE THREAD

**Issue by jesuGMZ** [TeamSQL/desktop-app#274]
Having a table with a column named _database_ if I try to apply an update it fails since the field `database` is not being scapped.

Example of a table with this case:

```
CREATE TABLE `sample_table` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `database` varchar(100) COLLATE utf8_bin DEFAULT NULL,
)
```

This is the query generated by _Apply_ button:

```
UPDATE `sample_table` SET  database = 'new value here' WHERE `id` = 1;`
```

**Comment by murteza** [comment]
Hi @jesuGMZ , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by jesuGMZ** [comment]
Tested and working!

This was the query generated by the update action:
```sql
UPDATE `semstest_ser`.`aa_sample_table` SET  `database` = 'tes' WHERE `id` = 1;
```
Great work guys, thanks!

PD: I got high CPU load with this version. Doing a fast check comes from the process `packagekitd`.
