### ISSUE TITLE
Redis commands not working with Redis 4.0

### ISSUE THREAD

**Issue by urossmolnik** [TeamSQL/desktop-app#277]
TeamSQL successfully connects to Redis but commands don't execute. They are stuck at "Running...".  
Tried with keys and scan.

I tried with 3 different deployments.

**Comment by selcukkiziltug** [comment]
Hi @urossmolnik, how can we reproduce this issue? We need some more detail of the commands that are not working.

**Comment by urossmolnik** [comment]
I can't reproduce this anymore with the latest release.
