### ISSUE TITLE
`Syntax error at or near " "`

### ISSUE THREAD

**Issue by imsrgadich** [TeamSQL/desktop-app#279]
A very vague error message, can this be made more informative? For the matter of fact the query was bug free and works on other applications.

thanks.

**Comment by murteza** [comment]
Hi @imsrgadich 

can you send us an example?

Thank you.

**Comment by imsrgadich** [comment]
I'm sorry I'm unable to share the sql query. But you might want to add line number to the error message would be more helpful. thanks.

**Comment by murteza** [comment]
Hi @imsrgadich , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by imsrgadich** [comment]
Thank you.
