### ISSUE TITLE
Trying to connect to an unauthorized database over postgres TLS makes all windows freeze

### ISSUE THREAD

**Issue by mstgelais** [TeamSQL/desktop-app#280]
Hi

I'm on Ubuntu Budgie 18.04. I'm connecting to a remote postgres 9.6 server over TSL (https://www.postgresql.org/docs/9.6/static/ssl-tcp.html).

Everything is working great, but when I try to open a database I don't have access to (no rule is set for this database in pg_hba.conf), the whole windowing system freezes. Opening a terminal with CTRL+ALT+F1 and killing the TeamSQL process is the only solution I have so far. I suppose that the correct behavior would be to display an error message.

If you need more detail, screenshots or anything, don't hesitate to ask!

**Comment by mryanmay** [comment]
@mstgelais were you able to get TeamSQL installed in 18.04? I'm not even able to get that working. If I can get that working, I can try to verify your issue.

**Comment by mstgelais** [comment]
I had to manually install **libgconf2.4** and **libcanberra-gtk-module**. I tweeted your team about it on May 2. I guess you didn't get the memo. ;-)

https://twitter.com/MattSinge/status/991688677205135360

Thanks a lot for looking into this!

**Comment by mryanmay** [comment]
@mstgelais I ran into the same issues you did. First, I had to install libgconf-2-4 manually. After that, I experience the same freezing you described when trying to connect to a DB I don't have access/authorization. Looks like the TeamSQL guys have created a bug for this. Nice!!

**Comment by mstgelais** [comment]
@mryanmay Thanks for confirming the bug. Bugs that can be easily reproduced are usually easier to fix. ;-)

@murteza Thanks for adding this to the bug list!

**Comment by murteza** [comment]
Hi @mstgelais @mryanmay , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
