### ISSUE TITLE
App freezes with no windows displayed no way around but to quit on startup after login

### ISSUE THREAD

**Issue by arjavmehta** [TeamSQL/desktop-app#281]

**Comment by murteza** [comment]
Hi @arjavmehta 

Can you provide more detail about your system information? (your OS, your TeamSQL version etc..)

Thank you.

**Comment by arjavmehta** [comment]
macOS 10.13.5, along with TeamSQL latest update 3.4.207.

**Comment by arjavmehta** [comment]
That worked thank you.
