### ISSUE TITLE
Persistent connections

### ISSUE THREAD

**Issue by markfsuk** [TeamSQL/desktop-app#283]
Every time you execute a query in TeamSQL it reconnects to the database. This has a significant time overhead, it would be much more efficient to use a persistent connection.

**Comment by jamesfsuk** [comment]
Closely related to #257 which looks like a real pain.

**Comment by gkurts** [comment]
I travel full time and am frequently on a slow connection. Having to re-establish the database connection every time definitely has a lot of overhead. If the application could keep the connection open, but do a quick check to reconnect if needed before query execution, it would drastically improve the experience.

**Comment by selcukkiziltug** [comment]
Hi @markfsuk , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback. Fyi @jamesfsuk @gkurts

**Comment by markfsuk** [comment]
@selcukkiziltug - Alas I see an issue immediately when trying the latest beta. Connections time out immediately when connecting to our Redshift instance, and work fine in the previous version. Connections to Aurora and our local MariaDB instances are fine however.

p.s. I like the new tab placement.

**Comment by selcukkiziltug** [comment]
Hi @markfsuk, let me check with the team and get back to you with more information.

**Comment by murteza** [comment]
Hi @markfsuk ,

Can you try TeamSQL V4.0.270?

Thank you.

**Comment by murteza** [comment]
Hi @markfsuk ,

We’ll fix this known issue with the next beta version. 
So, please stay tuned!

--
Erol from TeamSQL

**Comment by murteza** [comment]
There is a bug which we will fix in [TeamSQL 4.0.307](https://teamsql.io/nightly). Please stay tuned!
