### ISSUE TITLE
Inline Editing Not Working

### ISSUE THREAD

**Issue by carolineware** [TeamSQL/desktop-app#285]
OS: Windows_NT x64 10.0.16299
VERSION: 3.4.207
---------------
Database Type: PostgreSQL
When I try to edit a cell in the Output by typing it in and clicking Apply, the query always results in 0 applied changes.

**Comment by selcukkiziltug** [comment]
Hi @carolineware, is there a Primary Key in your table? 

Selcuk from TeamSQL

**Comment by murteza** [comment]
Hi @carolineware , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
