### ISSUE TITLE
Feature Request: Script templates

### ISSUE THREAD

**Issue by carolineware** [TeamSQL/desktop-app#287]
It would be great if you could use a script template like PGAdmin. For instance, you could select Insert Script for a table and not have to type out all the column names.

**Comment by murteza** [comment]
Hi @carolineware ,

We will add your request to our roadmap.
Meanwhile, you can use our SQL Generator extension.
![screen shot 2018-08-08 at 17 22 23](https://user-images.githubusercontent.com/1109510/43844537-a4c0c50e-9b32-11e8-91d8-9fc3ed4d6f9b.png)

How to download :

1. Click the extension tab on the left side.
2. Search SQL Generator
3. Click to install button.
