### ISSUE TITLE
'Test Connection' result dialogs

### ISSUE THREAD

**Issue by PrzemyslawMikos** [TeamSQL/desktop-app#29]
When I want to test remote connection while adding it, I'm able to click 'Test Connection' several times, and I get multiple result dialogs. This is not a big issue but in my opinion once you click it you cant click it again until result dialog appears. 
Screenshot: [https://ibb.co/gRZiJv](url)

**Comment by abacigil** [comment]
Thanks for the feedback, we'll be fixing it in the next release.

**Comment by erenbaydemir** [comment]
Fixed
