### ISSUE TITLE
Not Receiving Account Confirmation Emails

### ISSUE THREAD

**Issue by jeffw59** [TeamSQL/desktop-app#297]
OS: Windows_NT x64 10.0.17134
VERSION: 3.4.207
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?
Hi There

I have installed and registered but have not received the confirmation email despite selecting resend multiple times.

No being blocked by spam filter as far as I can tell.

Thanks

**Comment by selcukkiziltug** [comment]
Hi @jeffw59,

Let me check with the team and get back to you with more information.

Selcuk from TeamSQL

**Comment by selcukkiziltug** [comment]
Hi @jeffw59, we see that your activation mail has been sent to your inbox. However, we activated your account manually.

**Comment by cwcoffman** [comment]
I have the same issue - both myself and a team member.  I'm locked out now.  Been able to reset my password (twice) so I know the emails will come through.  But nothing in my account (including Junk) so far!  Please help.
