### ISSUE TITLE
Display character varying[] types

### ISSUE THREAD

**Issue by iaforek** [TeamSQL/desktop-app#299]
Currently, when I connect to a database that has a table with `character varying[]` type column all data is displayed as `BLOB` in TeamSQL.

Expected outcome: data displayed correctly.

**Comment by selcukkiziltug** [comment]
Hi @iaforek, 

Thanks for the comment. Let me check with the team and get back to you with more information.

Selcuk from TeamSQL

**Comment by murteza** [comment]
Hi @iaforek , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
