### ISSUE TITLE
Autocomplete does not work with aliases

### ISSUE THREAD

**Issue by AcerxX** [TeamSQL/desktop-app#30]
OS: Linux x64 4.4.0-65-generic
VERSION: 0.9.46
---------------
Database Type: MySQL, PostgreSQL
How can this issue be reproduced?

1. Create table my_table with columns id and name
2. Open new SQL tab.
3. Type: SELECT * FROM my_table AS mt WHERE mt.<something>...

When pressing . a popup appears with suggestions, but none of the columns of my_table is present there.

It should also work without de "AS" keyword (example: "SELECT * FROM my_table mt WHERE mt.<something>...").

**Comment by AcerxX** [comment]
On PostgreSQL auto complete does not work at all.

**Comment by abacigil** [comment]
Hi, we're working on it and public release will be stable for all engines.

Thanks.
