### ISSUE TITLE
Can't Cancel A Query

### ISSUE THREAD

**Issue by acholonu** [TeamSQL/desktop-app#301]
OS: Darwin x64 17.6.0
VERSION: 3.4.207
---------------
Database Type: PostGres

Was running a query.  The query was taking a long time to process.  Tried to cancel it with the cancel button.  Nothing happened.  It continued to run.  Please fix.

Thanks!

**Comment by zhihong** [comment]
Same issue here. 
OS: Windows 10 Pro
TeamSQL Version: 3.4.207
I am new to use teamSQL. My case, also because the query took long time. After "cancel", the log mentioned the connection is closed, but the Execute button keeps "running", and can not be used again.

**Comment by selcukkiziltug** [comment]
Hi @acholonu & @zhihong 

Let me check with the team and get back to you with more information. 

Selcuk from TeamSQL

**Comment by selcukkiziltug** [comment]
Hi @revbingo, we fixed this issue on the beta version of TeamSQL 4 which will be released soon. Please get it at http://teamsql.io/nightly.
