### ISSUE TITLE
Implement options to improve security of password storage

### ISSUE THREAD

**Issue by nneul** [TeamSQL/desktop-app#302]
Please either

A) Add ability to leave password blank with option to "prompt at connection time". (If you support connections without a password, then you'd likely need to make this a choice on the connection for whether to prompt or connect w/o a pw.)

        or

B) Add option for a "master passphrase" used to encrypt all credentials before storing in config file - and just prompt for that master passphrase when starting up the app or first opening a connection.

Even better - do both.

Right now, connection details are stored in cleartext in a file in user home dir:

 .config/TeamSQL/AppCache/users/###/connections.json

If you leave the password field on a connection blank, it just errors out when you try to connect instead of prompting, which means it's essentially unusable unless you save the password for the connection in the app.

**Comment by selcukkiziltug** [comment]
Hi @nneul, 

Many thanks for the detailed comment on this issue. A feature is on the way, so please stay tuned! 

Selcuk from TeamSQL

**Comment by nneul** [comment]
Looks like 3.4.230 is now encrypting config file! Thank you.
