### ISSUE TITLE
Cannot see tables only logins for mssql db

### ISSUE THREAD

**Issue by jbdhacf** [TeamSQL/desktop-app#303]
OS: Windows_NT x64 10.0.16299
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

**Comment by selcukkiziltug** [comment]
Hi @jbdhacf, 

Can you specify us the steps before you get this problem? 

Selcuk from TeamSQL

**Comment by murteza** [comment]
Hi @jbdhacf , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
