### ISSUE TITLE
Feature suggestion - Right click menu on results table cells options for filtering

### ISSUE THREAD

**Issue by nneul** [TeamSQL/desktop-app#304]
Add a "Filter" submenu on the right click menu that would populate the filter header as a quick shortcut.

- Filter
  - Exact
  - Contains
  - Starts With
  - Ends With

I was thinking mentally like the Wireshark "Prepare filter ... and / or / ... " type stuff to build up query automatically. This would only be feasible if you are parsing the query text in the editor. 

- Prepare Where (add to where clause)
  - and equals
  - and contains
  - and starts with
  - and ends with
  - or equals
  - or contains
  - or starts with
  - or ends with
- Apply Where (add to where clause and immediately execute)
  - ...

**Comment by abacigil** [comment]
Hi there,

You can filter the result sets using our Quick & Advanced Filtering features. It does not query to your database while filtering your data, but it filters in returned results.

Demo: http://recordit.co/5dWxfV5Jb5

**Comment by nneul** [comment]
Yes, I know... Was thinking at least for the interactive functionality it would save copy+paste or hand typing in the filter box as you are browsing the table.

**Comment by nneul** [comment]
Also looks like there is no way to do a contains/startswith/endswith in the advanced filtering.
