### ISSUE TITLE
 Query Timeout: Request failed to complete in 600000ms

### ISSUE THREAD

**Issue by tomas-ray** [TeamSQL/desktop-app#306]
OS: Windows_NT x64 6.1.7601
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

Connected MSSQL on AWS
Got the time out issue when running query with duration more than 10 mins

**Comment by selcukkiziltug** [comment]
Hi @tomas-ray, let me check with the team and get back to you with more information.

**Comment by selcukkiziltug** [comment]
Hi again @tomas-ray, we fixed this issue on the beta version of TeamSQL 4. Now you are able to set the timeout manually. Please download it at [http://teamsql.io/nightly](http://teamsql.io/nightly) and try to reproduce. Your feedback for the beta is appreciated.
