### ISSUE TITLE
Connections aren't all killed when you click disconnect

### ISSUE THREAD

**Issue by SkipMike** [TeamSQL/desktop-app#310]
OS: Linux x64 4.15.18-custom
VERSION: 3.4.230
---------------
Database Type: Postgresql
How can this issue be reproduced?
Connect to a database
Right click and disconnect
Try to drop the database outside of TeamSQL. Error because object in use. 
Close TeamSQL, attempt to drop the database, success.

**Comment by selcukkiziltug** [comment]
Hi @SkipMike , thanks for reaching out to us. Let me check with the team and get back to you with more information.

Selchuk from TeamSQL

**Comment by erenbaydemir** [comment]
In TeamSQL 3, we create separate connections for each tab, so disconnecting from the left connections pane doesn't affect the connections in tabs. However, we received similar complaints about this and we have changed this behaviour in TeamSQL 4 Beta. All tabs are using common connections in the beta (we'll add an option to keep separate connections), so disconnecting in the treeview will also disconnect the tabs and this issue will not be experienced.

**Comment by murteza** [comment]
Hi @SkipMike , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

--
Erol from TeamSQL
