### ISSUE TITLE
Redis opening keys in DB

### ISSUE THREAD

**Issue by deogo** [TeamSQL/desktop-app#311]
OS: Windows_NT x64 10.0.17134
VERSION: 3.4.230
---------------
Database Type: Redis
How can this issue be reproduced?
Double clicking any key in any db calls something like
GET spring:session:sessions:expires:5bc62e31-f8d1-4ce0-9813-7f9b1749f28c
which causing lot of errors
the key should be quoted, like
GET "spring:session:sessions:expires:5bc62e31-f8d1-4ce0-9813-7f9b1749f28c"

**Comment by selcukkiziltug** [comment]
Hi @deogo, we fixed this issue on TeamSQL 4.0 Beta release. You can download it from [http://teamsql.io/nightly](http://teamsql.io/nightly).
