### ISSUE TITLE
Keep connection to database alive

### ISSUE THREAD

**Issue by itssimon** [TeamSQL/desktop-app#313]
I'm using TeamSQL with PostgreSQL 9.5 hosted on AWS RDS.

It seems that TeamSQL does not keep a connection to the database alive. Issuing a query after a few minutes of inactivity always leads to a "Your server connection is down." message followed by "TeamSQL will try to reconnect and execute your query".

While I appreciated the automated reconnect, it is rather slow. For simple queries I often wait up to 10 seconds before I see a result, because TeamSQL has to reconnect.

It would be great if it could keep the connection alive for as long as TeamSQL is running.

**Comment by selcukkiziltug** [comment]
Hi @itssimon, thank you for reaching out to us. Some of our other users reported this issue, and we'll fix it with the next version of TeamSQL. Until then, you can download the TeamSQL 4 Beta to preview the fixed version at [http://teamsql.io/nightly](http://teamsql.io/nightly)  Please try to reproduce the issue and send us your feedback.
