### ISSUE TITLE
PostgreSQL array type showing as BLOB in results pane

### ISSUE THREAD

**Issue by itssimon** [TeamSQL/desktop-app#314]
TeamSQL does not display the values of array-type columns as featured by PostgreSQL. Instead the string _BLOB_ is shown in the results pane.

I would suggest showing the content of the array like
`[1, 2, 3]`

**Comment by krainboltgreene** [comment]
My only suggestion here is that it show up as `'{a, b, c}'` since that's how it's written: https://www.postgresql.org/docs/current/static/arrays.html#ARRAYS-INPUT

**Comment by selcukkiziltug** [comment]
Hi @itssimon, thank you for reaching out to us. And, thanks @krainboltgreene for the proper suggestion. We'll fix this issue with the next version of TeamSQL. Until then, you can download the TeamSQL 4 Beta to preview the fixed version at [http://teamsql.io/nightly](http://teamsql.io/nightly) Please try to reproduce the issue and send us your feedback.
