### ISSUE TITLE
Doesn't work with Heroku

### ISSUE THREAD

**Issue by dubcanada** [TeamSQL/desktop-app#318]
Hello,

Version: 4.0.256

There doesn't seem to be any way to connect to Heroku using the PostgreSQL database.

Using the Jetbrains DataGrip I can connect by doing http://andyfiedler.com/2016/02/getting-jetbrains-datagrip-to-work-with-heroku-postgres

Is there a way those options can be editable via some advanced setting or something? Jetbrains DataGrip uses JDBC that v4 uses so it should work.

Thoughts?

**Comment by selcukkiziltug** [comment]
Hi @dubcanada, thanks for reaching out to us. Let me check with the team and get back to you with more information.

**Comment by murteza** [comment]
Hi @dubcanada , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

--
Erol from TeamSQL

**Comment by jlebray** [comment]
@murteza Hi, http://teamsql.io/nightly redirects to http://teamsql.io. Is there another way to get the nightly version?

**Comment by murteza** [comment]
hi @jlebray ,

We released our stable version last week. Can try it on that version.

**Comment by otonielguajardo** [comment]
@dubcanada did you managed to connect to heroku through TeamSQL?

**Comment by 6temes** [comment]
I just tried and I couln't.

**Comment by otonielguajardo** [comment]
Seems like someone had the same problem recently #381
