### ISSUE TITLE
[Feature Request] Copy as Insert Statement

### ISSUE THREAD

**Issue by Elliotsmith** [TeamSQL/desktop-app#319]
TeamSQL seems really good.

I can see that you can copy as JSON, CSV etc, I'd really like the ability to copy results as an INSERT statement. I've been using a demo of Navicat and this is one of the features I really like, however, I'd much rather use this.

**Comment by selcukkiziltug** [comment]
Hi @Elliotsmith, I suggest you take a look at the extensions section and give a try at the "SQL Generator" extension. 
<img width="1552" alt="screen shot 2018-07-18 at 12 29 06" src="https://user-images.githubusercontent.com/15142906/42872712-56f66250-8a86-11e8-8abf-6ac527e06a1e.png">
