### ISSUE TITLE
Let me change the delay for the "Connection is taking too long - Keep connecting" message

### ISSUE THREAD

**Issue by rodbv** [TeamSQL/desktop-app#321]
Hi there,

I work on some PostgreSQL databases from across the globe, so there is some latency on the connection. So when I'm using TeamSQL I'm forced to keep clicking on that "Connection is taking too long - Cancel - Keep connecting" dialog a few times, it gets tiring.

It would be good to have an option to set a longer waiting time before you show that message, currently it seems to be around 5 seconds, I'd like to set it to 15 seconds or so.

Keep up the great work!

**Comment by selcukkiziltug** [comment]
Hi @rodbv , thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by selcukkiziltug** [comment]
Hi @revbingo, we added this feature on the beta version of TeamSQL 4 which will be released soon. Please get it at http://teamsql.io/nightly.
