### ISSUE TITLE
Sideload with 3.X, 4.X cannot connect to Postgres on Azure.

### ISSUE THREAD

**Issue by pedromvieira** [TeamSQL/desktop-app#322]
OS: Darwin x64 17.7.0
VERSION: 4.0.269
---------------
Database Type: Postgres on Azure
Same settings with side loaded 3.X branch (working), cannot connect to Postgres on Azure (Reason: Timeout)

**Comment by selcukkiziltug** [comment]
Hi @pedromvieira, thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
