### ISSUE TITLE
Configurable queries tab location

### ISSUE THREAD

**Issue by webernir** [TeamSQL/desktop-app#324]
In version 4, one of the major UI changes was the replacement of the vertical tabs bar in-favor of an horizontal tabs bar. 
Could it be possible to make this a settings option so the user can choose it's favorite style?

**Comment by selcukkiziltug** [comment]
Hi @webernir, thanks for the suggestion. A feature is on the way, so please stay tuned!

**Comment by webernir** [comment]
Awesome! 
that was one of your killing features.

**Comment by selcukkiziltug** [comment]
Hi again @webernir, there is a trick which I wanted to share with you; you can click the three dots at the top right corner of the app to open search bar. There you can see the vertical list of your tabs. Please, let me know if it works. 

We only show connections and DB items at the TreeView to give more information such as triggers and sequences.
