### ISSUE TITLE
ORACLE | After connect it don't stop object loading

### ISSUE THREAD

**Issue by jpfmeneses** [TeamSQL/desktop-app#328]
As I show on the attached image file, after I connnect to the ORACLE, it keeps loading the objects without let me start with querys.

The connection was succesfull tested on creation.

![tempsnip](https://user-images.githubusercontent.com/6529477/43252312-1447e2fa-90ba-11e8-8819-91ff8cbad1aa.png)

OS: Windows_NT x64 10.0.17134
VERSION: 4.0.270
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

**Comment by selcukkiziltug** [comment]
Hi @jpfmeneses, thanks for reaching out to us. Let me check with the team and get back to you with more information.

**Comment by murteza** [comment]
Hi @jpfmeneses , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

--
Erol from TeamSQL
