### ISSUE TITLE
When connected to postgres, I can see only one database

### ISSUE THREAD

**Issue by nachobi** [TeamSQL/desktop-app#329]
Just created connection without mark of “show only default database” shows only default database (Im using version 4.0.270)

here we can see that when connected only shows postgres database (I have more databases than postgres database)

<img width="599" alt="screen shot 2018-07-27 at 16 09 36" src="https://user-images.githubusercontent.com/15142906/43322535-84cc0efe-91b7-11e8-9c18-e95895c6f409.png">

here are the connection properties

<img width="599" alt="screen shot 2018-07-27 at 16 10 31" src="https://user-images.githubusercontent.com/15142906/43322563-9effb46a-91b7-11e8-8da9-02e5f55392b2.png">

I remember with previous versions I can see all my databases. It is very usable, because I work with one database, then switch to other database… Now I can’t see all my databases… it is a bug or is a “new feature “?

**Comment by selcukkiziltug** [comment]
Hi @nachobi , thanks for reaching out to us. Let me check with the team and get back to you with more information.

**Comment by selcukkiziltug** [comment]
Hi again, you need to add a new connection if the db you want to show is a different db type. For example, you cannot see your Oracle db in a Postgre kind of connection. If you want to see both of them, you need to add them separately by db type. Let me know if it works.

**Comment by nachobi** [comment]
Hi Selcuk
Yes, sure. I understand. However the issue I created is only for postgres databases. Is not related with Oracle testing.Ignacio

Enviado desde Yahoo Mail para Android 
 
  El vie 27 27e jul 27e 2018 a las 10:46 AM, Selcuk Kiziltug<notifications@github.com> escribió:   
Hi again, you need to add a new connection if the db you want to show is a different db type. For example, you cannot see your Oracle db in a Postgre kind of connection. If you want to see both of them, you need to add them separately by db type. Let me know if it works.

**Comment by murteza** [comment]
Hi @nachobi , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

--
Erol from TeamSQL
