### ISSUE TITLE
MySQL Bigints precision (zeros)

### ISSUE THREAD

**Issue by klichukb** [TeamSQL/desktop-app#33]
OS: Darwin x64 15.6.0
VERSION: 0.9.46
---------------
Database Type: MySQL 5.6
Q: How can this issue be reproduced?
A: 
1) Create a table with any column of type `bigint(20) unsigned`.
2) Create a record with a bigint value in it (not via TeamSQL), for example 4697992321105658095.
3) SELECT the record in TeamSQL and observe the returned bigint being 4697992321105658000. Notice last two digits being zeros. That happens to any number of such type.

**Comment by erenbaydemir** [comment]
Thank you @klichukb for reporting this. Issue is fixed and will be included in our next update.
