### ISSUE TITLE
Server Timezone AEST Unrecognized

### ISSUE THREAD

**Issue by seivad** [TeamSQL/desktop-app#333]
Hey got this error tonight using the beta build, couldn't really see anyway to get around it. Stable version works fine though.

**The server time zone value 'AEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.**

**Comment by selcukkiziltug** [comment]
Hi @seivad, thanks for reaching out to us. This known issue will be fixed with the next beta version. So, please stay tuned!
