### ISSUE TITLE
List materialized views in tree hierarchy

### ISSUE THREAD

**Issue by jqnatividad** [TeamSQL/desktop-app#334]
Currently, for PostgreSQL materialized views are not listed.

**Comment by selcukkiziltug** [comment]
Hi @jqnatividad, thanks for reaching out to us. Let me check with the team and get back to you with more detailed information.

**Comment by murteza** [comment]
Hi @jqnatividad , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

--
Erol from TeamSQL

**Comment by zzzace2000** [comment]
Hi murteza,
Where can I find the nightly build one? The link above is broken.
