### ISSUE TITLE
Option to 'close' chart unavailable.

### ISSUE THREAD

**Issue by shameer-ahwspl** [TeamSQL/desktop-app#336]
OS: Windows_NT x64 10.0.16299
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

When i try to open up charts after running a query, the buttons for closing, minimizing etc seems to go out of screen. The charts window is immovable so i am not able to drag the window down to reveal the Title bar buttons(resize,minimize,close)

![image](https://user-images.githubusercontent.com/37531169/43456402-fdc2dca8-94e0-11e8-8003-c659e536936e.png)

**Comment by selcukkiziltug** [comment]
Hi @shameer-ahwspl, thanks for reaching out to us. Let me check with the team and get back to you with more detailed information.

**Comment by abiaus** [comment]
I have the same trouble. Can't close Chart window after opening it, "ESC" button does nothing.
