### ISSUE TITLE
Column type binary(16) showing up as [object Object]

### ISSUE THREAD

**Issue by kflorence** [TeamSQL/desktop-app#337]
![bug](https://image.ibb.co/cVoYwK/Screen_Shot_2018_08_01_at_5_58_25_PM.png)

A `binary(16)` column displays as `[object Object]`.

TeamSQL Version 3.4.230 (3.4.230.230)

**Comment by selcukkiziltug** [comment]
Hi @kflorence, we'll fix this known issue with the next beta version. So, please stay tuned!

**Comment by murteza** [comment]
Hi @kflorence ,

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
