### ISSUE TITLE
Mysql: "show create table `my_table`;" return [object Object]

### ISSUE THREAD

**Issue by dominikzogg** [TeamSQL/desktop-app#344]

**Comment by murteza** [comment]
Hi @dominikzogg 

Thank you for reaching us. 
What is your TeamSQL version?

**Comment by dominikzogg** [comment]
OS: Linux x64 4.15.0-30-generic
VERSION: 3.4.230
---------------
Database Type: mysql

**Comment by murteza** [comment]
Hi @dominikzogg , 

This bug will be solve in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by dominikzogg** [comment]
@murteza thanks, is there also a .deb version? Not a fan of the .AppImage
