### ISSUE TITLE
Server TImezone

### ISSUE THREAD

**Issue by dominikzogg** [TeamSQL/desktop-app#345]
OS: Linux x64 4.15.0-30-generic
VERSION: 4.0.270
---------------
Database Type: mysql and mariadb
How can this issue be reproduced?

I've got the following error message trying to connect and have no idea howto fix it:

```
The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

```

**Comment by murteza** [comment]
Hi @dominikzogg ,

Thank you for reaching us. We’ll fix this known issue with the next version. 
So, please stay tuned!

**Comment by estyh** [comment]
I just downloaded 4.0.270 and tried to connect, got same error. On windows 10.
Is this related to this comment?
https://github.com/aaberg/sql2o/issues/243#issuecomment-403191414
