### ISSUE TITLE
two extra schemas showed when we open a database in a postgres connection

### ISSUE THREAD

**Issue by nachobi** [TeamSQL/desktop-app#346]
Hello

I think when we open a postgres database, we show 2 extra schemas ( information_schema , pg_catalog)  that don't need to be showed. these are internal postgres schemas 
![image](https://user-images.githubusercontent.com/10928144/43899741-45029ae8-9bb9-11e8-9dfb-febeca6e00c1.png)

2 correct examples in Navicat and  pgAdmin  SQL clients
In the following image of Navicat SQL client you can see the correct schemas to show
![image](https://user-images.githubusercontent.com/10928144/43899868-a042a83a-9bb9-11e8-82bd-e5a63e81915e.png)

In  pdAdmin client
![image](https://user-images.githubusercontent.com/10928144/43900061-20202500-9bba-11e8-81cc-c28b8ba87c06.png)

I will take a look into the postgres internal catalog, in order to detect the where clause to exclude the wrong schema names

**Comment by murteza** [comment]
Hi @nachobi ,

Thanks for reaching out to us. Let me check with the team and get back to you with more detailed information.

**Comment by nachobi** [comment]
Hi @selcukayhan 

Yes, you can still show . I only marked as a difference with other SQL clients that are more postgres oriented (like pgAdmin(native postgres) and Navicat for Postgres). The difference of those two schemas, is are implicity created, and regular users, dont have CREATE permission like they ussually have in "public" schema. Look for the C letter in the following image only present in public schema

![image](https://user-images.githubusercontent.com/10928144/43965288-4076fcf8-9c95-11e8-8f41-961f336ded11.png)
