### ISSUE TITLE
bug to start app

### ISSUE THREAD

**Issue by bachuesc** [TeamSQL/desktop-app#364]
OS: Linux x64 4.14.65-1-MANJARO
VERSION: 3.4.207
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?
* every time i start the application.
![image](https://user-images.githubusercontent.com/18581618/44488144-62bc1580-a62e-11e8-8979-696c3d91d416.png)

**Comment by selcukayhan** [comment]
Hi @bachuesc,

This case is related with Teamsql App's permissions on your OS. 

**Here is the solution :**

You should change ownership/permissions of config files via terminal for TeamSQL files.

Under your .config file you should see TeamSQL File.

Open terminal and type

 sudo chown -R <yourUserName>  .config/TeamSQL/

After that reboot your ubuntu and then TeamSQL App will be able to access your config files.

Thanks.

**Comment by bachuesc** [comment]
Hi selcukayhan,

First of all, my operating system is:
Distributor ID: ManjaroLinux
Description: Manjaro Linux
Release: 17.1.12
Codename: Hakoila

The second, you tell me to change the owner of the TEAMSQL directory but I do not understand which owner I should do it?
File Permissions
"bachuesc bachuesc 4096 Aug 22 12:40 TeamSQL"

Saludos Cordiales
Benjamin Achú Escobar

+56951247466 (tel:+56951247466)

**Comment by selcukayhan** [comment]
Hi @bachuesc,

I meant, you need to change owner of the config files directory or you need to give all permissions for this file. 

**For giving a permission;**
**For many of linux systems** Teamsql's **config** files being under the .config/TeamSQL directory.
Can you please type and run ' sudo chown -R .config/TeamSQL/ ' in terminal 
then Can you restart your Teamsql application?

**Comment by bachuesc** [comment]
the command 'chown -R .config/TeamSQL/' is misspelled.
I thought you knew
--
"chown: falta un operando después de «.config/TeamSQL/»
Pruebe 'chown --help' para más información."
--
I change the permissions of the directory ~ / .config / TeamSQL / to 'drwxrwxrwx' and the problem still persists.
The owner of the directory is me, I mean "bachuesc bachuesc"

I believe that the application tries to install a package * .deb and my operating system does not accept it, because as I said before, by default I use "Manjaro" derived from "ArchLinux"
On another computer I have the same version of TeamSQL installed, but the base operating system is Debian 9, and I have no problem. ;-)
Cheers,

Saludos Cordiales
Benjamin Achú Escobar

+56951247466 (tel:+56951247466)
