### ISSUE TITLE
Support password prompts for each connection

### ISSUE THREAD

**Issue by ramonsnir** [TeamSQL/desktop-app#366]
There should be a way (and there might be one, but didn't find it) to have TeamSQL prompt for a password on each connection. Either by not saving the password and asking for it every time, or maybe by encrypting the credentials with a passphrase that needs to be entered.

Using TeamSQL 3.4.

**Comment by murteza** [comment]
Hi @ramonsnir , 

Thank you for reaching out to us. We fixed this bug in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.
