### ISSUE TITLE
Connect to Oracle database as SYSDBA

### ISSUE THREAD

**Issue by maciek16180** [TeamSQL/desktop-app#367]
I can't find an option to connect to Oracle database as SYSDBA role. Is it possible right now?

I am using the latest nightly build. Normal Oracle connections work fine.

**Comment by murteza** [comment]
Hi @maciek16180 ,

Thank you for reaching out to us. Let me check with the team and get back to you.
So, please stay tuned!

**Comment by fatihdervisi** [comment]
Hi @maciek16180, 

If you want to connect to the oracle database as SYSDBA, you can fill the username field like this: 

![orcl-sysdba-screenshot](https://user-images.githubusercontent.com/15928141/45536907-7c0a4900-b80b-11e8-9758-a1c7a64ed783.png)
