### ISSUE TITLE
caching_sha2_password causes ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by WalterMarch** [TeamSQL/desktop-app#369]
OS: Linux x64 4.15.0-20-generic
VERSION: 3.4.230
---------------
Database Type: MySQL 8.0.12
How can this issue be reproduced?
If the `plugin` field is set to `caching_sha2_password` for the user, you'll get this error:

**Connection failed to the server. Please check your connection settings.**
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client.

**Comment by murteza** [comment]
Hi @WalterMarch , 

Thank you for reaching out to us. We fixed this bug in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by WalterMarch** [comment]
Yes, the 4.0-beta allows me to connect. Kudos on this and the UI improvements.

BTW, the test connection worked great but the actual connection didn't work until I ran through the steps in the pop-up about changing ownership. If you can, I would change part of it to say something like:
`Open terminal and type sudo chown -R <username> .config/TeamSQL/`
I know it is painfully obvious to most Linux users but I'm trying to move from Windows to Linux and those few extra characters would have saved me a little aggravation.

And while I'm making suggestions, since it was so important to do that chown-ing and reboot, you might want to make this statement a little clearer as to the reason you want to do it:
After that, reboot your Ubuntu and then TeamSQL App will be able to access your config files.
something like "or sh!t won't work." In your words, of course ;)

Thanks again! I'm on my way to connecting to my different database engines through *one tool*. Woot!
