### ISSUE TITLE
MS SQL connection: Server requires encryption, set encrypt config option to true

### ISSUE THREAD

**Issue by WalterMarch** [TeamSQL/desktop-app#371]
OS: Linux x64 4.15.0-20-generic
VERSION: 3.4.230
---------------
Database Type: MS SQL Server
How can this issue be reproduced?
Trying to connect to one of our Microsoft SQL servers, I get this error:

**Connection failed to the server. Please check your connection settings.**
Server requires encryption, set 'encrypt' config option to true.

but there doesn't appear to be any way to set that?

**Comment by murteza** [comment]
Hi @WalterMarch , 

Thank you for reaching out to us. This feature will be available in the next version of TeamSQL. And, it’s already in the latest beta version. You can download and test it at http://teamsql.io/nightly. We appreciate your feedback.

**Comment by WalterMarch** [comment]
I do **not** get this error in 4.0.307. Thanks.
