### ISSUE TITLE
Wrong processing fields tinyint(1)

### ISSUE THREAD

**Issue by a2nt** [TeamSQL/desktop-app#377]
OS: Linux x64 4.17.0-3-amd64
VERSION: 4.0.307
---------------
Database Type: MySQL
How can this issue be reproduced?
field type tinyint(1) displayed wrong as b'110001' while it shall be displayed as 1 - phpMyAdmin works ok with it.

**Comment by murteza** [comment]
@a2nt , I notice that you are using our latest beta version. You can download the stable version from [here.](https://teamsql.io/)

Thank you.

**Comment by selcukayhan** [comment]
Hi @a2nt,

We fixed this issue on our last release(4.0.357), you can download it from [Here](https://teamsql.io/)

Thank you.
