### ISSUE TITLE
Checkbox for Show Only Default Database Doesnt work

### ISSUE THREAD

**Issue by arkangel1611** [TeamSQL/desktop-app#378]
OS: Darwin x64 17.7.0
VERSION: 4.0.341
---------------
Database Type: MS SQL
How can this issue be reproduced?

Check "Show Only Default Database" still you are able to see all the Database in the RDS

**Comment by murteza** [comment]
Hi @arkangel1611 ,

Thank you for reaching out to us. Let me check with the team and get back to you.

--
Erol from TeamSQL

**Comment by arkangel1611** [comment]
@murteza this feature is not working for Redis.. can you please look into this again

**Comment by murteza** [comment]
Hi @arkangel1611 ,

Can you try with TeamSQL 4.0.376?

Thank you.
