### ISSUE TITLE
Not able to run any DML query with ANY clause present without schema name

### ISSUE THREAD

**Issue by arkangel1611** [TeamSQL/desktop-app#379]
OS: Darwin x64 17.7.0
VERSION: 4.0.341
---------------
Database Type: {MS SQL}

Default Schema for the User is dbo

select * from table_name; Works
select * from table_name where column_name=value; Does Not Work
select * from [dbo].[table_name] where column_name=value; Works

**Comment by murteza** [comment]
Hi @arkangel1611 ,

We try to reproduce your issue. But we didn't get any error. I'm sharing our test result screenshot. Can you help us to reproduce your issue?

Thank you.

![image 7](https://user-images.githubusercontent.com/1109510/45088560-05d25c00-b112-11e8-8f43-1f3feaeabcfc.png)
![image 5044baad-db0b-4d56-a7f1-9f4a1cd3b15b](https://user-images.githubusercontent.com/1109510/45088561-05d25c00-b112-11e8-9e4b-e9e265d14a2d.png)

**Comment by arkangel1611** [comment]
<img width="1076" alt="screen shot 2018-09-05 at 11 30 21 pm" src="https://user-images.githubusercontent.com/16644376/45112040-304d0500-b164-11e8-806d-f2fd6e5dc331.png">
<img width="1078" alt="screen shot 2018-09-05 at 11 31 49 pm" src="https://user-images.githubusercontent.com/16644376/45112042-304d0500-b164-11e8-86a9-df28cd4cdac5.png">
<img width="1080" alt="screen shot 2018-09-05 at 11 33 04 pm" src="https://user-images.githubusercontent.com/16644376/45112043-30e59b80-b164-11e8-9845-dc8c2c7540f3.png">
<img width="1074" alt="screen shot 2018-09-05 at 11 35 43 pm" src="https://user-images.githubusercontent.com/16644376/45112135-73a77380-b164-11e8-8a86-2f0ca5f518d0.png">

**Comment by aaronsturm** [comment]
I'm experiencing this as well on Ubuntu 18.04.1.

**Comment by arkangel1611** [comment]
@murteza any update ??

**Comment by barisozanguler** [comment]
Hi @arkangel1611 ,

We fixed this bug and it will send on next update in a few days. 

Thanks.

**Comment by arkangel1611** [comment]
@barisozanguler Thanks for the update..
