### ISSUE TITLE
Hung randomly

### ISSUE THREAD

**Issue by mrabchevskiy** [TeamSQL/desktop-app#380]
OS: Linux x64 4.15.0-33-generic, UBUNTU 18.04, UNITY desktop
VERSION: 4.0.341
---------------
Database Type: MariaDB
Some queries hung TeamSQL despite query is executed successfully; click on 'stop' square lead to normal finishing. The same query may hang or not hang randomly.

How can this issue be reproduced?

**Comment by murteza** [comment]
Hi @mrabchevskiy ,

We’ll fix this known issue with the next version. 
So, please stay tuned!
