### ISSUE TITLE
Is your app a scam?

### ISSUE THREAD

**Issue by wweaver** [TeamSQL/desktop-app#384]
https://www.google.com/search?q=Sunset+Lake+Rd%2C+Suite+B-2%2C+Newark%2C+19702%2C+Delaware+%2F+USA&oq=Sunset+Lake+Rd%2C+Suite+B-2%2C+Newark%2C+19702%2C+Delaware+%2F+USA&aqs=chrome..69i57.431j0j7&sourceid=chrome&ie=UTF-8

It seems like the address on your site is Deleware, your employees live and work in Turkey. That address is associated with many other businesses. I guess it's a tax break, hopefully you aren't a shady company.

**Comment by abacigil** [comment]
Hi @wweaver 

Thanks for the question. Of course our app is not a scam :) 

Our company is located in USA and also Turkey. 

Please check our company TeamSQL, Inc. from the links below:

Crunchbase: https://www.crunchbase.com/organization/teamsql-inc
Angel.co : https://angel.co/teamsql
D&D: https://www.dnb.com/
Delaware Department of State: https://icis.corp.delaware.gov/ecorp/entitysearch/namesearch.aspx

Please let us know your further questions.

Thanks,
