### ISSUE TITLE
The option to save my script locally 

### ISSUE THREAD

**Issue by jbaehne** [TeamSQL/desktop-app#393]
I really like this tool, however, I want to save some of my scripts locally some time. I end up wearing a lot of hats, and I would say 90% of the time I am good with the cloud save. The other 10% though I would like to save locally or to a specific folder on my work station for development purposes. 

Also, Git integration might be nice as well.

**Comment by murteza** [comment]
Hi @jbaehne ,

Thank you for reaching out to us. Let me check with the team and get back to you if we will consider adding to our roadmap.
So, please stay tuned!

**Comment by murteza** [comment]
Hi @jbaehne ,

We discuss your feature request with our team and we do not intend to do in the near future.
Thank you.
