### ISSUE TITLE
duplicate (save as) queries is not working

### ISSUE THREAD

**Issue by claireramming** [TeamSQL/desktop-app#395]
OS: Darwin x64 17.7.0
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?
1. open query you want to duplicate
2. hit the duplicate button in top right
3. change or leave default new query name
4. hit duplicate
5. you are returned to the original query and no new query was made/saved

I've been seeing this behavior for a bit over a week

**Comment by murteza** [comment]
Hi @claireramming ,

Can you update your version to 4.0.371? You can download from our [website.](https://teamsql.io/).

Thank you.

**Comment by claireramming** [comment]
Updated and seems to be working now. Thanks!
