### ISSUE TITLE
Won't format document.

### ISSUE THREAD

**Issue by mgrabenstein** [TeamSQL/desktop-app#398]
OS: Darwin x64 17.7.0
VERSION: 3.4.230
---------------
Database Type: Redshift
This sql:
insert into
  dateTable
select
  cast(
    '2018-09-11T15:00:00.000' as timestamp without time zone
  ) as start_date,
  cast(
    '2018-09-11T21:00:00.000' as timestamp without time zone
  ) as end_date,
  dateadd(
    'month',
    -3,
    cast(
      '2018-09-11T15:00:00.000' as timestamp without time zone
    )
  ) as start_date_lookback;

Will not complete format document.

**Comment by murteza** [comment]
Hi @mgrabenstein ,

Thank you for reaching out to us. We’ll fix this known issue with the next update. Also, I notice that you're using 3.4 version of TeamSQL. We released a new version last month (TeamSQL 4.0). You can download from our [website.](https://teamsql.io) 
So, please stay tuned!

**Comment by mgrabenstein** [comment]
Thank you.
