### ISSUE TITLE
Add SSH tunnel 

### ISSUE THREAD

**Issue by pomirleanu** [TeamSQL/desktop-app#40]

**Comment by abacigil** [comment]
Thanks, it'll be available with the next version : > 0.9.81

**Comment by simonds** [comment]
@abacigil The 3/24 milestone doesn't exist anymore. Can you add it to the 3/31 milestone? https://github.com/TeamSQL/desktop-app/milestone/5

**Comment by hoektoe** [comment]
Any updated on this? Just downloaded today to use for local environment first. Wanted to connect to dev db on mysql but could not as I require ssh :(

So far looking very nice compare to boring sequelpro

**Comment by erenbaydemir** [comment]
We've completed coding for SSH Tunnels today. We will be doing some polishing and start testing and hopefully it will be available this week's update. 

![ssh](https://cloud.githubusercontent.com/assets/688276/24596425/e4266ef2-1847-11e7-94c6-52808a40ca48.png)

**Comment by abacigil** [comment]
Released on v0.9.84

**Comment by pomirleanu** [comment]
Also could add ssh key, personally i do not use password!

**Comment by abacigil** [comment]
Hi @pomirleanu 
You can set a private key file also, here:

![screen shot 2017-04-11 at 08 09 45](https://cloud.githubusercontent.com/assets/759174/24893754/56bf971c-1e8e-11e7-8db5-aa9cd8bb4b5e.png)
