### ISSUE TITLE
Team SQL throws HOST UNREACHABLE error 

### ISSUE THREAD

**Issue by bmukund21** [TeamSQL/desktop-app#400]
![teamsql error](https://user-images.githubusercontent.com/41670174/45809921-0ad50500-bce7-11e8-84bb-cebafdf8e157.JPG)
OS: Windows_NT x64 10.0.17134
VERSION: 4.0.371

My internet is working fine and firewall access is given.
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

**Comment by murteza** [comment]
Hi @bmukund21 ,

If you're using a proxy or something, please allow *.teamsql.io domains, or you can configure your proxy settings by clicking "Proxy Settings" button in the red bar.
 
Let me know if you have any questions.
