### ISSUE TITLE
Don't open full-screen

### ISSUE THREAD

**Issue by ianleeder** [TeamSQL/desktop-app#401]
Can you please either remember the last window size, or set a reasonable one by default?  Every time I open TeamSQL it opens full size (on macOS it's not technically full-screen like the green button does, but it's a window that takes up the entire screen size).  On a 2560x1440 screen this is ridiculously big, and sits on top of all my other windows until I resize it again.

**Comment by murteza** [comment]
Hi @ianleeder ,

Thank you for reaching out to us. What is your TeamSQL version? We added this feature on TeamSQL 4 version. You can download from our [website](https://teamsql.io/).

**Comment by mkismy** [comment]
Same issue here. 

TeamSQL 4.0.371
macOS 10.13.6

**Comment by murteza** [comment]
Hi @mkismy ,

I can't reproduce your issue. 
You can look my demo video from here :
![pyazet1xjw](https://user-images.githubusercontent.com/1109510/45943797-7b826700-bff0-11e8-8960-8cc759761a27.gif)

**Comment by mkismy** [comment]
Hi @murteza , 
After rebooting mac, it started to work as your screen recording.
I'm not sure why but it may be occurring only on the first install?

**Comment by ianleeder** [comment]
Hi @murteza,
TeamSQL prompts me reasonably regularly to update (which I do), so I assumed I was on the latest version.  Evidently not, I'm running 3.4.230.  I'll go download 4 and try again, thanks.
