### ISSUE TITLE
Not receiving verification email, do not know how to change email associated with install

### ISSUE THREAD

**Issue by mpettis** [TeamSQL/desktop-app#407]
OS: Darwin x64 17.6.0
VERSION: 4.0.371
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

Just downloaded last week.  Asking me to verify account through email sent to me.  I have not received email to use to verify.  Perhaps the account, a work one, is blocking it.  I do not know how to change my email account associated with it (to one I think I can receive the email in).  Please advise.

**Comment by rjreeves** [comment]
Hi @mpettis ,
Try sign-out (button bottom left corner). Then you should be asked for an email address for a new email address.

Hope this helps.

**Comment by murteza** [comment]
Hi @mpettis  ,

We checked our mail services and it works fine. We need your email address to investigate your issue. Please do not write on Github your email address. Send an email to support@teamsql.io about your case.

If you want to change your email address, please send an email to support@teamsql.io.

Let me know if you have any questions.

**Comment by cwcoffman** [comment]
This is also reflected in "Not Receiving Account Confirmation Emails #297" and I'm experiencing it, along with a teammate now.  Thanks for looking into it!  I sent an email with both our addresses to the support@teamsql.io address, as suggested above.
