### ISSUE TITLE
When support Aurora MySQL?

### ISSUE THREAD

**Issue by YuK1Game** [TeamSQL/desktop-app#412]
It does not exist in the roadmap.
Correspond to Aurola?
![ws000000](https://user-images.githubusercontent.com/20548753/46139380-5b210980-c289-11e8-9d2c-20f884a190d5.JPG)

thanks.

**Comment by selcukkiziltug** [comment]
Hi, you can use the standard MySQL option to connect the Aurora database. Only advanced features like Snippets not supported. That's why we added it to the coming soon section.
