### ISSUE TITLE
Wont connect to MySQL and keeps displaying a popup

### ISSUE THREAD

**Issue by agentwolf44** [TeamSQL/desktop-app#414]
OS: Windows_NT x64 10.0.17134
VERSION: 4.0.379
---------------
Wont connect to MySQL and keeps displaying a popup saying:
"Java Development Kit is required to connect MySQL databases. TeamSQL uses JDBC drivers for MySQL connections.
You can download latest JDK version from here."

I've downloaded all files necessary and installed them to no avail. The message appears no matter what I do.

**Comment by murteza** [comment]
Hi @agentwolf44 ,

Thanks for reaching out to us. What is your JDK version?

**Comment by agentwolf44** [comment]
Should be the latest one, so version 11

**Comment by murteza** [comment]
@agentwolf44 ,

Can you check your JDK version (using Command Prompt) ?

**Comment by agentwolf44** [comment]
> java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

(I had to fix the java paths in the environment paths, but that still didn't fix the TeamSQL problem, if you were wondering)

**Comment by agentwolf44** [comment]
Update: Nevermind, that did end up fixing it. Thanks for the help!
