### ISSUE TITLE
MS SQL Express - Cannot connect to local MS SQL Express instance

### ISSUE THREAD

**Issue by hellfire17** [TeamSQL/desktop-app#416]
**Environment**: Windows 10 x64

**Steps to Reproduce**:

1. Download and install the latest version (4.0.379) of TeamSQL
2. Start to create a new connection for SQL Server 
3. Enter the parameters shown in the attached screenshot
4. Click the "Test Connection" button  

**Expected**: 
1. The connection test should be successful (_since the previous stable version of TeamSQL was able to connect to the same SQL Express instance_)

**Actual**:
1. The error message shown in the attached screenshot is shown
![sqlexpress_error](https://user-images.githubusercontent.com/43722251/46257331-1dc3b280-c4fb-11e8-9b55-e867bb6e9a02.png)

**Comment by Akhil-Das** [comment]
Hi check the port number which you have provided is correct.

**Comment by hellfire17** [comment]
Hey, I checked the port and it seems to be correct. I've attached a screenshot of the configuration so that we are on the same page.

![sql server configuration manager](https://user-images.githubusercontent.com/43722251/46278397-5d48d800-c5a9-11e8-9c75-b1ee60bbfa0d.png)

**Comment by selcukayhan** [comment]
Hi @hellfire17 ,

There is a known issue about Windows AUTH as [Windows Authentication to SQL server is not working in Latest Beta](https://github.com/TeamSQL/desktop-app/issues/358) and we are on it to fix. 

If you have a chance to authenticate with SQL SERVER AUTH, you can use that method for a while.

Thanks for you understanding.

**Comment by hellfire17** [comment]
Hey, I see. I will wait for the bug you have mentioned to be fixed. 
Thanks for your quick response, and keep up the good work!

**Comment by murteza** [comment]
#358
