### ISSUE TITLE
Can not double click to do inline editing.

### ISSUE THREAD

**Issue by stormz514** [TeamSQL/desktop-app#421]
OS: Windows_NT x64 10.0.17763
VERSION: 4.0.379
---------------
Database Type: MySQL
How can this issue be reproduced?
1. Connect database.
2. Open a table
3. Double click on existing data cell in selected table.

**Comment by murteza** [comment]
Hi @stormz514 

Did you get any error message?

**Comment by selcukkiziltug** [comment]
Hi @stormz514, we tried to reproduce this issue, and everything went well. Please contact us at support@teamsql.io if you need further help.
