### ISSUE TITLE
Windows Auth fails in version 4 for MSSQL

### ISSUE THREAD

**Issue by mhball** [TeamSQL/desktop-app#422]
OS: Linux x64 4.4.0-135-generic
VERSION: 4.0.379
---------------
Database Type: MS SQL Server
How can this issue be reproduced?

I cannot log in the the DB server using Windows Authentication. This works fine with identical settings in version 3.4.230.

**Comment by selcukayhan** [comment]
Hi @mhball ,

Thank you for reaching us,
This is a known issue as [#358](https://github.com/TeamSQL/desktop-app/issues/358) and we will fix it soon. 

Thank you.
