### ISSUE TITLE
[Redshift] Can't query Redshift Spectrum

### ISSUE THREAD

**Issue by ponkon** [TeamSQL/desktop-app#433]
When I try to query a Redshift Spectrum table with TeamSQL I get:

`[Amazon](500310) Invalid operation: schema "spectrum" does not exist;`

However the same query works when I run it in `psql`.

I'm guessing this is because Redshift Spectrum tables are considered "External Schemas" and aren't created in the same way that regular redshift tables are, however they are supposed to be queried as if they're the same.

**Comment by selcukayhan** [comment]
Hi @ponkon,

I am able to create external tables, connect and execute scripts on Redshift Spectrum my scripts are below. Would you please send us details about your issue and your TeamSQL Client's version? 

<img width="1440" alt="screen shot 2018-10-22 at 18 23 21" src="https://user-images.githubusercontent.com/23242811/47301615-f8245780-d627-11e8-9f6c-7808ca2f4a94.png">

**Comment by ponkon** [comment]
You are 100% correct - my issue was I wasn't selecting the correct database in the upper right corner of the UI. Once I selected the database on which my spectrum schema was created on it worked perfectly.

Looking forward to using TeamSQL! Sorry you had to go through the debugging to find that everything did indeed work...
