### ISSUE TITLE
中文支持

### ISSUE THREAD

**Issue by YiHan-HuaHua** [TeamSQL/desktop-app#435]
如何切换中文版本

**Comment by selcukkiziltug** [comment]
Hi @YiHan-HuaHua, thanks for reaching out. Sorry, we can't support the Chinese language for now. (Translated your question in Google Translate. I hope this is the proper answer to your question.) When we see the huge interest from Chinese users, it's possible to add support in the near future. Thanks for choosing TeamSQL, and please stay tuned.
