### ISSUE TITLE
Oracle - Show only default database doesn't work

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [TeamSQL/desktop-app#441]
*OS: Arch Linux*
*Database: Oracle EE 12.2c*
*TeamSQL: v4.0.392*

---

Hi there!

We are evaluating a SQL client to substitute Oracle SQL Developer, and TeamSQL looks very promising.

In our application we have many microservices, each one with it's own database, and for that we have many owners to connect to.

When I added an Oracle connection in TeamSQL, I set the owner (username / password), set the default database (which is the username), set the default database (the username, again), and checked "Show only default database".

After that I opened a query window to test some SQL, and TeamSQL asked for me to choose between all usernames available in the database, ignoring the default database configuration, and mainly the "show only default database". Since I'm connecting using a restrict username, I can only access tables from that user. If I choose by mistake a different user other than the configured one on the connection, I'll get access denied in all SQLs.

This issue was addressed in #378, but I didn't see a solution there.

Is this a bug related to Oracle connections? We can't use TeamSQL if we will have to choose between hundreds of usernames for each connection.

Best regards,
Rafael Pacheco.

**Comment by selcukayhan** [comment]
Hi @rafaelrenanpacheco ,

Thank you for reaching out us, we will fix this issue on next Release.
