### ISSUE TITLE
No output for EXPLAIN queries.

### ISSUE THREAD

**Issue by mpmlj** [TeamSQL/desktop-app#45]
Hi,

On running explain on a query, ex. 
EXPLAIN SELECT * FROM "public"."users" LIMIT 200;
there's no result, just a log record ("Output" tab).

**Comment by abacigil** [comment]
Hi @mpmlj it's a small bug in our datalayer. We found it and it'll be fixed asap.

**Comment by abacigil** [comment]
Hi @mpmlj , we've just released a new update that fixes this issue. Please update your TeamSQL, version 0.9.87 will fix this.

**Comment by mpmlj** [comment]
Thank you!
