### ISSUE TITLE
Keep getting logged out.

### ISSUE THREAD

**Issue by RomainDebo** [TeamSQL/desktop-app#465]
OS: Windows_NT x64 10.0.17134
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

As i am typing in a query, TeamSQL will log me out and present the sign-in page.

**Comment by chris-gpc** [comment]
This is happening to a coworker and I as well.

**Comment by martineasy** [comment]
Same here.

Error text:
Error when validating logged in user information. Please sign in again.

**Comment by allanino** [comment]
I'm facing the same issue.

Error text:

`Error when validating logged in user information. Please sign in again.`

**Comment by muffinlab** [comment]
Same / Similar. 

I was logged out with the message: 

> Error when Validating logged in user information. Please Sign in again. 

...now it doesn't seem to accept my email as already existing - attempts to sign me up as a new user. When I do submit my email address, it says "user already exists with this email."

**Comment by j-wil** [comment]
I got logged out and now when I enter my email for my account it prompts me to create a new account.

**Comment by umbrella-alexey-reznikov** [comment]
The same is for Mac version. Seems something wrong with a sign-in subsystem on the server :/

**Comment by JuanELo-O** [comment]
The same is happening to me, I executed from terminal (Ubuntu 18.10), and it shows me the following error:

`Cannot check for updates: HttpError: 403 Forbidden
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>0110BA99C00AE97B</RequestId><HostId>bZfMT6v6dQbtF/MZB9B4E3XTSio8h8VsWNbReHmjlhg4p6wne9i40uW1y3rRbuJ0NstIKs4MiFY=</HostId></Error>"
Headers: {
  "age": [
    "78"
  ],
  "connection": [
    "keep-alive"
  ],
  "content-type": [
    "application/xml"
  ],
  "date": [
    "Wed, 26 Dec 2018 16:32:56 GMT"
  ],
  "server": [
    "AmazonS3"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "via": [
    "1.1 fb8e6daa39bc4124e46750734008822c.cloudfront.net (CloudFront)"
  ],
  "x-amz-cf-id": [
    "B2T1ilpgOlv9Ws1h4ZSEGscwnZ8J3uDvDbadeA2fBQI1F92JJgtcMw=="
  ],
  "x-cache": [
    "Error from cloudfront"
  ]
}
`

It seems like a cloudfront error.

**Comment by JesKingDev** [comment]
Mac OS Mojave 10.14.2
TeamSQL version 3.4.230
Same issue as described by previous comments
Thought it was my version at first, so tried to upgrade to v4. However, the website link to the latest version of the client is also broken - https://teamsql.io/download?os=osx.

**Comment by Koen87** [comment]
Same for me.. Is it part of an update..?

**Comment by garretttaco** [comment]
I am having the same issue. It will not let me even login. It just keeps repeating the error message:
```Error when validating logged in user information. Please sign in again.```

**Comment by kermes** [comment]
+1

**Comment by StephenWork** [comment]
Same issue. Cant login.

**Comment by michaelmadani** [comment]
> I am having the same issue. It will not let me even login. It just keeps repeating the error message:
> `Error when validating logged in user information. Please sign in again.`

I have the same error, has anyone found a way to locate the local .sql queries that were saved through TeamSQL? I am assuming their is a local copy stored somewhere but I am not seeing it.

**Comment by rupeshgardi04** [comment]
same for me.. not working

**Comment by selcukkiziltug** [comment]
There was a server problem affecting some users. TeamSQL is up and running for all users now. Please try again.
