### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by tangelaine** [TeamSQL/desktop-app#466]
OS: Windows_NT x64 10.0.17134
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

Open the TeamSQL app and get to the 'Get Started' screen. There is no place to log in; it asks you to sign up, then has a red error box without any text (I'm guessing the error says I already have an account, which I do).

**Comment by jjh5166** [comment]
Same issue with mac os 10.14.1

**Comment by dsblank** [comment]
Same issue for Ubuntu.

**Comment by DanielBodnar** [comment]
ditto

**Comment by michaelmadani** [comment]
I am having the same issue with my Mac

**Comment by narisso** [comment]
Same issue with mac. The app sends me to the welcome screen and there's no place to sign in. Signup fails with an empty red box.

**Comment by peiroupl** [comment]
Same issue here.

**Comment by peiroupl** [comment]
And tried some archived-versions, issue persisted.

**Comment by karishmagarewal** [comment]
Same issue with mac.

**Comment by Ryan-Robinson** [comment]
Same!!

**Comment by garretttaco** [comment]
Related to #465 I believe.

**Comment by brunolm** [comment]
Download page for Windows redirects to `/undefined`, not sure if related

**Comment by bottae** [comment]
same here ;;

**Comment by mbhavik91** [comment]
Same here

**Comment by df-karuna** [comment]
Same here, 10.14 MacOS.

**Comment by hemantksh** [comment]
Same problem since 10 hours back. Something is wrong with the backend. Please fix asap.

**Comment by macchiang** [comment]
same here.

**Comment by mike-audi** [comment]
same

**Comment by nadesh-hatchster** [comment]
I am also having same issue from morning. please let me know how can i fix it.

**Comment by nadesh-hatchster** [comment]
Now it is working after reinstall the app. thanks

**Comment by timesking** [comment]
On Mac, I deleted ~/Library/Application Support/TeamSQL. it fixed

**Comment by selcukkiziltug** [comment]
There was a server problem affecting some users. TeamSQL is up and running for all users now. Please try again.
