### ISSUE TITLE
not getting logged in even signup not working 

### ISSUE THREAD

**Issue by rupeshgardi04** [TeamSQL/desktop-app#467]
OS: Linux x64 4.15.0-42-generic
VERSION: 3.4.230
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

**Comment by openskullbox** [comment]
Observing the same issue with MacOS Sierra (10.12.6), TeamSQL version 4.0.392

What happened:
All of a sudden today I get the error "Error when validating logged in user information. Please sign in again". Then during registration it shows an empty red box without any error message.

Looks like an issue at the backend validation. But don't have more info. If there's a place where I can check the validation API calls, let me know.

**Comment by selcukkiziltug** [comment]
There was a server problem affecting some users. TeamSQL is up and running for all users now. Please try again.
