### ISSUE TITLE
Cannot see tables in public postgres schema

### ISSUE THREAD

**Issue by rmchale** [TeamSQL/desktop-app#48]
OS: Darwin x64 16.4.0
VERSION: 0.9.81
---------------
Database Type: postgres
How can this issue be reproduced?

When I connect to my database it does not show me all schemas.  In particular I do not see the tables in the public schema in the left pane.

**Comment by abacigil** [comment]
Fixed

**Comment by rmchale** [comment]
What version is this fixed in?  I am still seeing this issue on `0.9.91`

**Comment by abacigil** [comment]
@rmchale You see "public" schema in the list but tables in "public" schema, right?

**Comment by rmchale** [comment]
It doesn't list any tables

https://www.dropbox.com/s/joq0cy1j29hiib9/Screenshot%202017-04-26%2009.51.21.png?dl=0

**Comment by MetaDonk** [comment]
I am seeing same thing.
