### ISSUE TITLE
Cannot connect on SQL server with Windows Authentication behind a VPN

### ISSUE THREAD

**Issue by ventouris** [TeamSQL/desktop-app#51]
I use to connect on a MSSQL server with Windows Authentication using a VPN. I duplicate the settings from another program I use at the moment in MacOS, but it doesn't work. It says that I need to check the connection again.

What extra info do you need for debugging?

**Comment by abacigil** [comment]
Hi,

If you select Windows Authentication for MSSQL, TCP/IP connection must be enabled for that MSSQL Server so you can use your Windows username and password for the authorization.

Please check: https://technet.microsoft.com/en-us/library/hh231672(v=sql.110).aspx

**Comment by ventouris** [comment]
TCP/IP is enabled on the server and I am able to connect with other apps on both Mac and Windows.

**Comment by Evilnames** [comment]
Can +1 this also.  Tried connecting to a server and checked TCP/IP which is on.

**Comment by Andware** [comment]
I can not connect to MSSQL server with Windows Login. Do not use firewall or VPN.
It's like it's not trying to connect to the server when selecting Windows Authentication

![skaermbillede_2017-04-06_kl__11_03_34](https://cloud.githubusercontent.com/assets/3460191/24746320/ffb3d93e-1ab8-11e7-9083-da1cebb0dd0f.png)

**Comment by abacigil** [comment]
Domain name is case sensitive, can you try to write it considering case sensivity?

**Comment by ventouris** [comment]
I managed to connect to the Database, but when I click on the new query window, I have a pop up with "retrieve database list" and stuck there
