### ISSUE TITLE
Scrollbars in results table

### ISSUE THREAD

**Issue by josser** [TeamSQL/desktop-app#52]
OS: Darwin x64 16.4.0
VERSION: 0.9.81
---------------
Database Type: PostgreSQL 

Sometimes scrollbars appears in results browser.

![2017-03-24 16 56 25](https://cloud.githubusercontent.com/assets/103639/24299824/164b8f9e-10b3-11e7-8305-a3bd16e3787d.png)

**Comment by abacigil** [comment]
Fixed
