### ISSUE TITLE
Results data grid doesn't resize when the results pane is manually resized.

### ISSUE THREAD

**Issue by erenbaydemir** [TeamSQL/desktop-app#53]
Results data grid should snap to bounds and resize if the container resizes. But it retains the calculated height on rendering. 

![bug](https://cloud.githubusercontent.com/assets/688276/24321240/98f3af94-1158-11e7-8b1c-aca5e3e67e95.png)

**Comment by sitefinitysteve** [comment]
I THINK this is the same issue?  But would be nice to get some intelligent resizing based on content like min-widths on Guids or dates... autoscale the rest or something, just too much wasted space.

![image](https://cloud.githubusercontent.com/assets/1542376/24556167/7f296952-1601-11e7-8810-463970253dae.png)

**Comment by abacigil** [comment]
Fixed
