### ISSUE TITLE
No SSL Support with Redshift

### ISSUE THREAD

**Issue by pankajsaini0803** [TeamSQL/desktop-app#58]
OS: Linux x64 4.8.0-41-generic
VERSION: 0.9.81
---------------
Database Type: Redshift
How can this issue be reproduced?
Redshift clusters which enforce SSL for connections can not be connected via TeamSQL because there is no option to specify ssl=true. It would be great if connection URL could be custom.

**Comment by abacigil** [comment]
It'll be available with next update. Duplicate of https://github.com/TeamSQL/desktop-app/issues/47
