### ISSUE TITLE
Cannot sign in or sign up

### ISSUE THREAD

**Issue by enchoir** [TeamSQL/desktop-app#62]
OS: Windows_NT x64 6.3.9600
VERSION: 0.9.81
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

email: enchoir@gmail.com
Sign in:
Incorrect email or password when trying to sign in, "forgot password" doesn't work (did not receive any email).
Sign up:
"This email address is already being used by a TeamSql user".

**Comment by anasbousselham** [comment]
I have the same problem!!

**Comment by abacigil** [comment]
Will be fixed asap.

**Comment by abacigil** [comment]
Hi @enchoir @anasbousselham 

Are you using any firewall? If so, since TeamSQL is a new application and it doesn't have a security score yet, it might be the reason.

**Comment by miguelcabanes** [comment]
I have the same problem because i am behind proxy. What can i do, or where can i set proxy config?thanks

**Comment by abacigil** [comment]
We've released an update which has proxy support.

Please see details: https://github.com/TeamSQL/desktop-app/issues/112
