### ISSUE TITLE
Feature Request: Connecting status

### ISSUE THREAD

**Issue by sitefinitysteve** [TeamSQL/desktop-app#63]
Theres no feedback on the Add Connection (windows anyway) window.  When I hit test connection I would expect it to disable or something to let me know it's "trying"... right now I can click it 20 times and just not see anything happen, then I get 20 popups saying it failed :)

**Comment by erenbaydemir** [comment]
Hi! We've added an activity indicator inside the Test Connect button and now we disable it until the test completes. These changes will be included in our next update (to be released in this week).

![screen shot 2017-04-03 at 08 49 17](https://cloud.githubusercontent.com/assets/688276/24596820/7b553a90-184a-11e7-878e-9624472b322b.png)

**Comment by sitefinitysteve** [comment]
Some feedback is good!

I dont suppose you could just take it one tiny step further and improve the disabled UI state so the text is greyed out a bit (button doesn't dropshadow on hover) and maybe the text itself changes to "Testing..." or something.

Just a thought, better than what it was initially, defiantly!

**Comment by erenbaydemir** [comment]
Agreed!
