### ISSUE TITLE
Connection to AWS RDS Error

### ISSUE THREAD

**Issue by jacobthomasmichael** [TeamSQL/desktop-app#64]
OS: Darwin x64 16.4.0
VERSION: 0.9.81
---------------
Database Type: {MSSQL} using AWS RDS
How can this issue be reproduced?
* Click to add a new connection
* Input AWS settings
* Click 'Test Connection'
* Connection Test will say 'Successful'
   **Click Save/Close
* Attempt to connect to new connection
   ** Get Error Message 'Connection failed to the server. Please check your connection settings.'

If you edit the connection after the above message, and Test it again, it will say the connection is successful.

**Comment by abacigil** [comment]
Hi,

Which version of MSSQL are you using? Which authentication method did you use? Is it Windows Authentication or SQL Server Authentication?

Please also check this link it may help: http://help.teamsql.io/faq/connection-microsoft-sql-server-over-tcpip

If you give more details, we would like to help and solve it.

**Comment by abacigil** [comment]
I closed this issue due to insufficient information.
