### ISSUE TITLE
Table cell value editing

### ISSUE THREAD

**Issue by UnAfraid** [TeamSQL/desktop-app#71]
Hello,

I am missing a feature crucial to me, whenever i open a table i'd like to be able to edit the cell values, if primary key exists update with it, if not update based on all other fields.

Thanks!

**Comment by aewing** [comment]
Any update on this? I am literally waiting on this feature to purchase the Pro version of TeamSQL.

**Comment by ashatp** [comment]
+1

**Comment by eyalhakim** [comment]
+1

**Comment by lloydw** [comment]
+1

**Comment by jfanctil** [comment]
+1

**Comment by diegoiglesias** [comment]
+1000

**Comment by massimo-cassandro** [comment]
+1

**Comment by eSaner** [comment]
+1

**Comment by gregbenner** [comment]
+1

**Comment by fhals** [comment]
+1

**Comment by mykdin** [comment]
+1

**Comment by ToasterBR** [comment]
+1

**Comment by Stiropor** [comment]
+1

**Comment by abacigil** [comment]
Please update to 3.2.187 version, inline editing feature is now available.

Thanks,
