### ISSUE TITLE
Windows authentication fails on Mac os

### ISSUE THREAD

**Issue by Andware** [TeamSQL/desktop-app#77]
How can I fix this error? See printscreen!
![skaermbillede 2017-04-11 kl 07 54 57](https://cloud.githubusercontent.com/assets/3460191/24894690/5337eda8-1e8c-11e7-9d83-ce35c8913192.png)

Info:
OS: MacOS Sierra
SQL Server: SQL Server 2012 
Authentication: Windows Authentication
TCP/IP enabled on SQL Server

**Comment by abacigil** [comment]
Hi @Andware ,

DOMAIN name and other values ( such as username ) are case-sensitive, can you try to enter your these values considering case-sensitivity?

**Comment by abacigil** [comment]
@Andware are you in a Active Directory Domain?

**Comment by Andware** [comment]
Yes I am in a Active Directory Domain!
My mac is joined to Active Directory Domain.

**Comment by Andware** [comment]
Is there something new in this case

**Comment by Andware** [comment]
Today I have update to latest version. Now I can connect to SQL Server with Windows authentication. Thanks for fix it.
