### ISSUE TITLE
feature to enable SSL

### ISSUE THREAD

**Issue by akinuk80** [TeamSQL/desktop-app#78]
OS: Linux x64 4.4.0-72-generic
VERSION: 0.9.84
---------------
Database Type: PostgreSQL
How can this issue be reproduced?
I am trying to connect to PostgreSQL for which I need SSL "require" to be enabled that does not exist due to which I am unable to make a connection.

**Comment by abacigil** [comment]
Duplicate of https://github.com/TeamSQL/desktop-app/issues/47

**Comment by abacigil** [comment]
It's available with v0.9.86, we've just released it, please update.

**Comment by akinuk80** [comment]
Thank you, SSL is enabled that led me to access the database.
