### ISSUE TITLE
ANALYZE COMPRESSION  in Redshift doesn't work

### ISSUE THREAD

**Issue by ggiotta-DV** [TeamSQL/desktop-app#80]
OS: Darwin x64 16.5.0
VERSION: 0.9.84
---------------
Database Type: {Redshift}
How can this issue be reproduced?

ANALYZE COMPRESSION myTable

 doesn't produce any result (after running and complete)

**Comment by abacigil** [comment]
Hi @ggiotta-DV 

We found the bug and it'll be fixed asap.

Also duplicate of https://github.com/TeamSQL/desktop-app/issues/45

**Comment by abacigil** [comment]
Hi @ggiotta-DV  , we've just released a new update that fixes this issue. Please update your TeamSQL, version 0.9.87 will fix this.
