### ISSUE TITLE
Auto-updater not working

### ISSUE THREAD

**Issue by furtive** [TeamSQL/desktop-app#81]
Running macOS TeamSQL Private Beta v0.9.81 and it keeps showing a bar at the bottom saying Version 0.9.84 is available but when you press the "Restart & Install" button it just restarts, doesn't update to latest version. 
![image](https://cloud.githubusercontent.com/assets/22137/24931856/1f2835dc-1ecc-11e7-93b5-71ee0c084890.png)

**Comment by abacigil** [comment]
Can you try to reinstall TeamSQL? It's about a bug in Electron framework.

We're waiting a release from Electron that fixes this bug.

**Comment by kristiandupont** [comment]
This seems to be an issue still. After a while of looking at the bar in the screenshot, TeamSQL simply pushes through and starts the update with a system-wide modal dialog that steals focus. Could you maybe make it a little less aggressive, at least until it's been fixed?
