### ISSUE TITLE
Tunnel Not Connect

### ISSUE THREAD

**Issue by acarravedo** [TeamSQL/desktop-app#82]
OS: Darwin x64 16.5.0
VERSION: 0.9.86
---------------
Database Type: MySQL + Tunnel
How can this issue be reproduced?

Configure DB in localhost default port and connect using Tunnel in port 2222 with Private Key.

This configuration not connect and block firewall of remote server.

**Comment by erenbaydemir** [comment]
Hi. May I ask a few questions? 

- Do you setup an SSH tunnel using an external program? 
- If so, do you select SSH Tunnel in the add / edit connection screen?

**Comment by abacigil** [comment]
I closed this issue since there is no enough description.

**Comment by acarravedo** [comment]
Sorry, i don't view your questions.

I use tunnel from connection configuration ... and "test connection" button run ok ... but after this the connection icon in "list of servers" don't run ... "Connection failed to the server. Please check your connection settings".

I'm using key "Private Key File".
 
![image](https://cloud.githubusercontent.com/assets/1014060/25235762/6c09e4e2-25e6-11e7-8839-aa4e57fe8f76.png)

![image](https://cloud.githubusercontent.com/assets/1014060/25235772/74440642-25e6-11e7-995f-37c6e87a7c03.png)

**Comment by schiggi** [comment]
I've got the same problem with Win10 64x client. Test connection is ok, but it won't let me connect with the same "error" message. I am using as well a custom ssh port. And a custom mysql port. on the server itself.

**Comment by acarravedo** [comment]
I opened new issue with new data in ... [https://github.com/TeamSQL/desktop-app/issues/117](https://github.com/TeamSQL/desktop-app/issues/117)
