### ISSUE TITLE
Unable to connect to MSSQL 2008

### ISSUE THREAD

**Issue by shezan74** [TeamSQL/desktop-app#83]
OS: Windows_NT x64 6.3.9600
VERSION: 0.9.86
---------------
Database Type: MSSQL 2008
System reports "UNABLE TO CONNECT" but the same parameters are used in Oracle SQL Developer with MSSQL plugin and Sql Server tools and works ok
Server answers to PING correctly, port is 1433 default

**Comment by abacigil** [comment]
Hi, do you use Windows authentication? If yes, you need to enter a domain name ( if you don't have one, any value is also ok ).

Domain name must be *upper case*

Example: MYDOMAIN

Let me know if it fails.

**Comment by shezan74** [comment]
Hi, no i’m using SQL authentication

 



 

Same machine, it works with another client

 



 

Da: Can Abacigil [mailto:notifications@github.com] 
Inviato: giovedì 13 aprile 2017 20.11
A: TeamSQL/desktop-app <desktop-app@noreply.github.com>
Cc: shezan74 <lele@pisto.it>; Author <author@noreply.github.com>
Oggetto: Re: [TeamSQL/desktop-app] Unable to connect to MSSQL 2008 (#83)

 

Hi, do you use Windows authentication? If yes, you need to enter a domain name ( if you don't have one, any value is also ok ).

Domain name must be upper case

Example: MYDOMAIN

Let me know if it fails.

**Comment by abacigil** [comment]
Please check this: https://app.intercom.io/a/apps/pyjipnbq/educate/articles/651161/show

I also summarized most common problems here:

- You must enable SQL Server Browser Service and TCP/IP Connections.
- Are you trying to access your server with an instance name? If the server is accessible only with instance name, you must enter your instance name.
*Example* : db.myhost.com/INSTANCENAME

- Host name cannot be ".", if it's local, you must enter localhost or IP address.

- TCP/IP in SQL Server must be enabled. ( http://help.teamsql.io/faq/connection-microsoft-sql-server-over-tcpip )

- Host name (not connection name ) must not contain port number, "http" prefix or any other extra value than basic host name.
*Example* : my-sql-server.us-east-1.rds.amazonaws.com

- Default port is 1433 in TeamSQL, your server's port is 1433 or another one?

Let me know if you still have problems, or you can contact to us from Intercom, so we can ask more detailed questions.

**Comment by abacigil** [comment]
Hey @shezan74 ,

Any update for this? I think the reason is "SQL Server Browser" service is not working. Can you check that?

**Comment by gfilardi** [comment]
Hi! I'm trying to use SQL Server without success.

I do have:
SQL Server Browser enabled,
TCP/IP enabled, 
Connection working fine in other client (DBeaver).
Not using windows authentication.

Do you have anything different I can try?
Thanks.

**Comment by manuelro** [comment]
Same problem here. Can't connect to an SQL Server running inside a Docker container. I can connect to the very same instance using other clients, though (sqlectron).
