### ISSUE TITLE
Unable / Not apparent how to provide a passphrase for SSL into mysql

### ISSUE THREAD

**Issue by sneakypooka** [TeamSQL/desktop-app#84]
In making a connection to mysql, we use private keys with passphrases on them.   I am either not seeing a way to apply a passphrase or not able to provide a passphrase.   

Thanks for working on this, I see huge potential for this application!

**Comment by erenbaydemir** [comment]
Hi there! We just added SSL support but currently it's only available for PostgreSQL and Redshift. We will add SSL support for MySQL as well in the upcoming releases.
