### ISSUE TITLE
SSH tunnel doesn't work

### ISSUE THREAD

**Issue by masalitvv** [TeamSQL/desktop-app#85]
OS: Darwin x64 15.6.0
VERSION: 0.9.86
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

1) Setup ssh tunel using PostgreSQL connection driver
2) Press test connection (it says that connection successfully connected and then press Close & Save)
3) Try to connect from the main screen and it says that connection has failed
![2017-04-13_21-24-14](https://cloud.githubusercontent.com/assets/16563438/25018345/b47129c2-208f-11e7-8a15-25c64c7e8508.png)
![2017-04-13_21-22-55](https://cloud.githubusercontent.com/assets/16563438/25018346/b473c894-208f-11e7-9976-2606cfab6762.png)

**Comment by erenbaydemir** [comment]
Hi! Can you please confirm if that happens following those steps: 

1- Create a connection with incorrect SSH settings.
2- Try to connect using the Connections pane. 
3- Connection will fail
4- Edit connection, fix the SSH settings, test connection and see it's working. 
5- Save connection
6- Try to connect from the connections pane. 
7- Connection still fails

**Comment by masalitvv** [comment]
That was an original scenario which cause the issue. Then I added tunnel manually using ssh -N -L 5439:172.30.0.153:5439 sp.stat and created a new connection to localhost (which is ssh tunnel) and the behavior of teamSQL was absolutely the same.

Thanks!
