### ISSUE TITLE
Problem while getting columns while joining two tables with aliases

### ISSUE THREAD

**Issue by halilserkanuz** [TeamSQL/desktop-app#86]
OS: Darwin x64 16.5.0
VERSION: 0.9.87
---------------
Database Type: MySQL 5.7
How can this issue be reproduced?

Hi, 
 
While joining two tables with aliases, in select statement if I write "alias". lookup doesn't show fields of aliased table.

Select b.XID, count(distinct a.Id) /*after distinct write a. and it doesn't show fields of TableA */
 FROM TableA a
 INNER JOIN TableB b ON a.Id = b.TableAID
        Where a.CreateDate >= date_sub(now(), interval 24 hour)
        GROUP BY b.XID

**Comment by abacigil** [comment]
Hi there,

You're talking about code completion feature, right? If so, we're working on it.

Or is it something else?

**Comment by halilserkanuz** [comment]
Yes, it is about code completion. Thanks for your reply. Then we will wait. Thanks.
