### ISSUE TITLE
There is no notification if firewall blocks the app connection

### ISSUE THREAD

**Issue by OrkanCom** [TeamSQL/desktop-app#87]
OS: Windows_NT x64 6.3.9600
VERSION: 0.9.87
---------------
Database Type: N/A
How can this issue be reproduced?

I'm using Microsoft Windows 8.1 64x with all updates installed.

Issue is: There is no gui notification if the application can't connect to internet because of firewall.
I'm using [TinyWall 2.1.8](https://tinywall.pados.hu/) (currently, lastest) and it blocks unknown applications such as TeamSQL.exe.
The gui of TeamSQL should give a notification about this, like "TeamSQL can't connect to internet, please check your cable or firewall settings" etc. Now it responses like "nothing happen" if you push the button an ex: "forget password" at login screen. I think the app will response same way with other firewalls too.

**Comment by abacigil** [comment]
We've released an update which has proxy support. Proxy support is available with v0.9.106

Please see details: #112
