### ISSUE TITLE
Saving different queries from the same window

### ISSUE THREAD

**Issue by p0d3r** [TeamSQL/desktop-app#90]
OS: Windows_NT x64 10.0.14393
VERSION: 0.9.87
---------------
Database Type: {Related database type if applicable}
How can this issue be reproduced?

After saving a query, one should be able to save an another query (or modified query) with different name from the same window that's already open by using a shortcut like `ctrl + shift + s` / `cmd + shift + s`

**Comment by abacigil** [comment]
Completed
