### ISSUE TITLE
Autocomplete doesn't work on Redshift

### ISSUE THREAD

**Issue by ggiotta-DV** [TeamSQL/desktop-app#94]
OS: Darwin x64 16.5.0
VERSION: 0.9.87
---------------

**Comment by abacigil** [comment]
Hi @ggiotta-DV 

We're working on it and it'll be fixed for all database engines.

Thanks for the feedback.

**Comment by tarekkaddoumi** [comment]
still not working for redshift

**Comment by Rusbens1** [comment]
Bump

**Comment by AshleyRodanHP** [comment]
Just updated teamSQL and on on 3.2.195 and its not working for my redshift connection.

is this still an issue?
