### ISSUE TITLE
Connection with Tunnel not connect

### ISSUE THREAD

**Issue by acarravedo** [TeamSQL/desktop-app#96]
I use tunnel from connection configuration ... and "test connection" button run **OK** ... but after this the connection icon in "list of servers" don't run ... "**Connection failed to the server. Please check your connection settings**".

I'm using key "Private Key File".
 
![image](https://cloud.githubusercontent.com/assets/1014060/25235762/6c09e4e2-25e6-11e7-8839-aa4e57fe8f76.png)

![image](https://cloud.githubusercontent.com/assets/1014060/25235772/74440642-25e6-11e7-995f-37c6e87a7c03.png)

**Comment by erenbaydemir** [comment]
We identified and fixed the issue. The fix will be included in the next update. 

We actually have a problem in the edit connection window and SSH settings are cleared when the connection is updated. So SSH settings works well in add connection flow. As a workaround, you can try adding a new connection with the same settings until we release the update (should be in a few days).

**Comment by acarravedo** [comment]
Thanks, I'm waiting for release of the update.
