### ISSUE TITLE
MSSQL Server requires encryption error

### ISSUE THREAD

**Issue by flessard** [TeamSQL/desktop-app#98]
OS: Darwin x64 16.5.0
VERSION: 0.9.91
---------------
Database Type: MSSQL
I got this error when i try to add MSSQL database : Server requires encryption, set 'encrypt' config option to true. 

But there no option in connection window for encryption.

**Comment by paulsinnett** [comment]
Yes, I got this too.

**Comment by abacigil** [comment]
Hey @flessard @paulsinnett 

Sorry for that bug, we've fixed and we're releasing a new update today. It'll be fixed. Thanks.
